# -*- coding: utf-8 -*-
"""
Extended domain map for VC firms, accelerators, and prominent tech companies
to aid in email pattern generation and LinkedIn search enrichment.
"""

DOMAIN_MAP = {
    # Top VCs & Accelerators
    "Y Combinator": "ycombinator.com",
    "Sequoia": "sequoiacap.com",
    "Andreessen Horowitz": "a16z.com",
    "a16z": "a16z.com",
    "Kleiner Perkins": "kleinerperkins.com",
    "Accel": "accel.com",
    "Index Ventures": "indexventures.com",
    "Bessemer": "bvp.com",
    "Greylock": "greylock.com",
    "General Catalyst": "generalcatalyst.com",
    "Benchmark": "benchmark.com",
    "GV": "gv.com",
    "Google Ventures": "gv.com",
    "True Ventures": "trueventures.com",
    "Foundry Group": "foundrygroup.com",
    "Homebrew": "homebrew.co",
    "First Round": "firstround.com",
    "Spark Capital": "sparkcapital.com",
    "Union Square Ventures": "usv.com",
    "USV": "usv.com",
    "Techstars": "techstars.com",
    "500 Global": "500.co",
    "500 Startups": "500.co",
    "Atomico": "atomico.com",
    "Northzone": "northzone.com",
    "Seedcamp": "seedcamp.com",
    "Balderton": "balderton.com",
    "Earlybird": "earlybird.com",
    "Point Nine": "pointninecap.com",
    "Creandum": "creandum.com",
    "LocalGlobe": "localglobe.vc",
    "Partech": "partechpartners.com",
    "Kima Ventures": "kimaventures.com",
    "Upfront Ventures": "upfront.com",
    "Forerunner": "forerunnerventures.com",
    "Cowboy Ventures": "cowboy.vc",
    "SV Angel": "svangel.com",
    "Haystack": "haystack.vc",
    "Precursor": "precursorvc.com",
    "Pear VC": "pear.vc",
    "Blackbird": "blackbird.vc",
    "NEA": "nea.com",
    "Lightspeed": "lsvp.com",
    "IVP": "ivp.com",
    "Matrix Partners": "matrixpartners.com",
    "Social Capital": "socialcapital.com",
    "Revolution": "revolution.com",
    "Founders Fund": "foundersfund.com",
    "Khosla": "khoslaventures.com",
    "Khosla Ventures": "khoslaventures.com",
    "General Atlantic": "generalatlantic.com",
    "Tiger Global": "tigerglobal.com",
    "Coatue": "coatue.com",
    "Insight Partners": "insightpartners.com",
    "Battery Ventures": "battery.com",
    "Ribbit Capital": "ribbitcap.com",
    "Lux Capital": "luxcapital.com",
    "Air Street Capital": "airstreet.com",
    "Lerer Hippeau": "lererhippeau.com",
    "Theory Ventures": "theory.vc",
    "Redpoint Ventures": "redpoint.com",
    "Cherry Ventures": "cherry.vc",
    "Antler": "antler.co",
    "draper": "draper.vc",
    "emersoncollective": "emersoncollective.com",
    "startupbootcamp": "startupbootcamp.org",
    "rockstart": "rockstart.com",
    "indiebio": "indiebio.co",
    "backstagecapital": "backstagecapital.com",
    "Alchemist Accelerator": "alchemistaccelerator.com",
    "Entrepreneur First": "joinef.com",
    "MassChallenge": "masschallenge.org",
    "Plug and Play": "plugandplaytechcenter.com",
    "Pioneer": "pioneer.app",

    # Tech Companies often listed in bios
    "Stripe": "stripe.com",
    "Shopify": "shopify.com",
    "GitHub": "github.com",
    "Canva": "canva.com",
    "Figma": "figma.com",
    "Notion": "notion.so",
    "Webflow": "webflow.com",
    "Zapier": "zapier.com",
    "Twilio": "twilio.com",
    "Slack": "slack.com",
    "Zoom": "zoom.us",
    "HubSpot": "hubspot.com",
    "Salesforce": "salesforce.com",
    "OpenAI": "openai.com",
    "Airbnb": "airbnb.com",
    "DoorDash": "doordash.com",
    "Uber": "uber.com",
    "Google": "google.com",
    "Microsoft": "microsoft.com",
    "Meta": "meta.com",
    "LinkedIn": "linkedin.com",
    "Coinbase": "coinbase.com",
    "PayPal": "paypal.com",
    "Brex": "brex.com",
    "Plaid": "plaid.com",
    "Wise": "wise.com",
    "Klarna": "klarna.com",
    "Adyen": "adyen.com",
    "Grab": "grab.com",
    "Gojek": "gojek.com",
    "Flipkart": "flipkart.com",
    "Freshworks": "freshworks.com",
    "Zoho": "zoho.com",
    "Zalando": "zalando.com",
    "Stanford": "stanford.edu",
    
    # Specific known companies from the db
    "sevensevensix": "sevensevensix.com",
    "sahillavingia": "sahillavingia.com",
    "tinycapital": "tinycapital.com",
    "levels": "levels.io",
}
