# -*- coding: utf-8 -*-
"""
OpenAngels - Batch 5: Final push to 1000 investors
More US VCs, sector specialists, global angels
"""

INVESTORS_BATCH5 = [

# ═══════════════════════════════════════════
# INSIGHT PARTNERS - MORE TEAM
# ═══════════════════════════════════════════
{"name":"Hilary Gosher","bio":"Managing Director at Insight Partners. Expert in Israeli tech and cybersecurity.","location":"Tel Aviv","country":"Israel","type":"vc","check_min":10000000,"check_max":200000000,"stages":["series-b","growth"],"industries":["security","saas","enterprise","ai"],"portfolio":["Wix","monday.com","SentinelOne"],"verified":True},
{"name":"Teddie Wardi","bio":"Managing Director at Insight Partners. Expert in Nordic and Baltic tech startups.","location":"Helsinki","country":"Finland","type":"vc","check_min":5000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["saas","marketplace","fintech","enterprise"],"portfolio":["Pipedrive","Supermetrics"],"verified":True},

# ═══════════════════════════════════════════
# OPENAI / AI-NATIVE ANGELS
# ═══════════════════════════════════════════
{"name":"Sam Altman","bio":"CEO of OpenAI. Former president of Y Combinator. Prolific angel investor in AI and tech.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/sama","type":"angel","check_min":250000,"check_max":10000000,"stages":["pre-seed","seed","series-a"],"industries":["ai","saas","developer-tools","energy","biotech"],"portfolio":["Stripe","Reddit","Asana","Helion","Retro Biosciences"],"verified":True},
{"name":"Greg Brockman","bio":"Co-founder of OpenAI. Angel investor in AI infrastructure and safety.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/gdb","type":"angel","check_min":100000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["ai","developer-tools","safety","deep-tech"],"portfolio":["OpenAI"],"verified":True},
{"name":"Andrej Karpathy","bio":"Former OpenAI, former Tesla AI. Angel investor and advisor in deep learning and AI.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/karpathy","type":"angel","check_min":50000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["ai","developer-tools","deep-tech","robotics"],"portfolio":[],"verified":True},
{"name":"Ilya Sutskever","bio":"Co-founder of OpenAI and SSI. Pioneer in deep learning. Angel in AI safety research.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":100000,"check_max":5000000,"stages":["seed","series-a"],"industries":["ai","deep-tech","safety","developer-tools"],"portfolio":["OpenAI","SSI"],"verified":True},

# ═══════════════════════════════════════════
# FORMER Y COMBINATOR PARTNERS
# ═══════════════════════════════════════════
{"name":"Dalton Caldwell","bio":"Partner at Y Combinator. Co-founder of imeem. Expert in early-stage B2B and developer tools.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/daltonc","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["developer-tools","saas","ai","enterprise"],"portfolio":[],"verified":True},
{"name":"Michael Seibel","bio":"Partner at Y Combinator. Co-founder of Twitch and Justin.tv. Consumer video expert.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/mwseibel","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","media"],"portfolio":["Twitch","Justin.tv","Socialcam"],"verified":True},
{"name":"Garry Tan","bio":"President and CEO of Y Combinator. Co-founder of Initialized Capital. Early investor in Coinbase, Instacart.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/garrytan","type":"vc","check_min":500000,"check_max":10000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","ai","fintech","crypto"],"portfolio":["Coinbase","Instacart","Posthog","Deel"],"verified":True},
{"name":"Adora Cheung","bio":"Partner at Y Combinator. Co-founder of Homejoy. Expert in marketplace and future of work.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/adoracheung","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["marketplace","consumer","future-of-work","saas"],"portfolio":["Homejoy"],"verified":True},
{"name":"Gustaf Alstromer","bio":"Partner at Y Combinator. Former Airbnb growth lead. Expert in growth and consumer products.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/gustaf","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas","ai"],"portfolio":[],"verified":True},
{"name":"Kevin Hale","bio":"Partner at Y Combinator. Founder of Wufoo. Expert in product design and B2B SaaS.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/ilikevests","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["saas","developer-tools","consumer","marketplace"],"portfolio":["Wufoo"],"verified":True},
{"name":"Tim Brady","bio":"Partner at Y Combinator. Employee #1 at Yahoo. Advises on B2B SaaS and enterprise.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["saas","enterprise","developer-tools","marketplace"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════
# FINTECH VCs - ADDITIONAL
# ═══════════════════════════════════════════
{"name":"Hans Morris","bio":"Managing Partner at Nyca Partners. Former president of Visa. Expert in payments and fintech.","location":"New York, NY","country":"USA","type":"vc","check_min":2000000,"check_max":30000000,"stages":["series-a","series-b"],"industries":["fintech","payments","banking","saas"],"portfolio":["Stripe","Plaid","Marqeta","Blend"],"verified":True},
{"name":"Gali Ben-Joseph","bio":"General Partner at QED Investors. Expert in fintech across emerging and developed markets.","location":"Alexandria, VA","country":"USA","type":"vc","check_min":2000000,"check_max":30000000,"stages":["series-a","series-b"],"industries":["fintech","insurance","marketplace","saas"],"portfolio":[],"verified":True},
{"name":"Frank Rotman","bio":"Co-founder of QED Investors. Former Capital One. Leading fintech VC.","location":"Alexandria, VA","country":"USA","twitter_url":"https://twitter.com/fintechjunkie","type":"vc","check_min":2000000,"check_max":30000000,"stages":["series-a","series-b"],"industries":["fintech","marketplace","saas","insurance"],"portfolio":["Credit Karma","SoFi","Avant","Nubank"],"verified":True},
{"name":"Nigel Morris","bio":"Co-founder of QED Investors and Capital One. Expert in fintech and consumer credit.","location":"Alexandria, VA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b","growth"],"industries":["fintech","banking","consumer","marketplace"],"portfolio":["Credit Karma","SoFi","Klarna","Nubank"],"verified":True},

# ═══════════════════════════════════════════
# MORE US SEED FUNDS
# ═══════════════════════════════════════════
{"name":"Roy Bahat","bio":"Head of Bloomberg Beta. Expert in future of work and emerging technologies.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/roybahat","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["future-of-work","saas","ai","developer-tools","media"],"portfolio":[],"verified":True},
{"name":"Evan Nisselson","bio":"General Partner at LDV Capital. Expert in visual technology, AI, and computer vision.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/enisselson","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["ai","computer-vision","deep-tech","saas"],"portfolio":[],"verified":True},
{"name":"David Frankel","bio":"Managing Partner at Founder Collective. Expert in contrarian early-stage investing.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/davidfrankel","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","developer-tools"],"portfolio":["Uber","Buzzfeed","Codeacademy"],"verified":True},
{"name":"Eric Paley","bio":"Managing Partner at Founder Collective. Expert in lean, capital-efficient startups.","location":"Cambridge, MA","country":"USA","twitter_url":"https://twitter.com/epaley","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","developer-tools","marketplace"],"portfolio":["Uber","Buzzfeed","PillPack"],"verified":True},
{"name":"Micah Rosenbloom","bio":"Managing Partner at Founder Collective. Expert in early-stage B2B and developer tools.","location":"Cambridge, MA","country":"USA","twitter_url":"https://twitter.com/micahjay1","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","developer-tools","enterprise","marketplace"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════
# VILLAGE GLOBAL
# ═══════════════════════════════════════════
{"name":"Erik Torenberg","bio":"Co-founder of Village Global and On Deck. Expert in community-led investing.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/eriktorenberg","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","creator-economy","ai"],"portfolio":["Openai","Scale AI","Robinhood"],"verified":True},
{"name":"Ben Casnocha","bio":"Co-founder of Village Global. Author of 'The Start-Up of You'. Expert in talent and networks.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/bencasnocha","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","future-of-work"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════
# TENCENT / ALIBABA INVESTMENT ARMS
# ═══════════════════════════════════════════
{"name":"James Mitchell","bio":"Chief Strategy Officer at Tencent. Oversees Tencent's $70B+ global investment portfolio.","location":"Shenzhen","country":"China","type":"vc","check_min":5000000,"check_max":500000000,"stages":["series-a","series-b","growth"],"industries":["gaming","consumer","fintech","saas","ai"],"portfolio":["Snap","Tesla","Spotify","Epic Games"],"verified":True},
{"name":"David Wei","bio":"Former CEO of Alibaba.com. Active investor in China and Southeast Asian tech.","location":"Hangzhou","country":"China","type":"angel","check_min":1000000,"check_max":20000000,"stages":["series-a","series-b"],"industries":["e-commerce","marketplace","saas","fintech"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════
# MIDDLE EAST INVESTORS
# ═══════════════════════════════════════════
{"name":"Omar Christidis","bio":"Founder of ArabNet. Angel investor in Arab tech ecosystem. Expert in MENA startups.","location":"Dubai","country":"UAE","twitter_url":"https://twitter.com/omarchristidis","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","fintech","consumer"],"portfolio":[],"verified":True},
{"name":"Khaled Talhouni","bio":"Managing Partner at Wamda Capital. Expert in Arab world tech and entrepreneurship.","location":"Amman","country":"Jordan","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["marketplace","saas","fintech","consumer"],"portfolio":[],"verified":True},
{"name":"Walid Hanna","bio":"Founding Partner at Middle East Venture Partners (MEVP). Pioneer of Lebanese and Arab VC.","location":"Beirut","country":"Lebanon","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","marketplace","fintech","consumer"],"portfolio":[],"verified":True},
{"name":"Fadi Ghandour","bio":"Co-founder of Aramex. Founder of Wamda. Pioneer entrepreneur and investor in Arab world.","location":"Amman","country":"Jordan","twitter_url":"https://twitter.com/fadig","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["logistics","marketplace","saas","fintech","consumer"],"portfolio":["Aramex","Maktoob"],"verified":True},

# ═══════════════════════════════════════════
# SCANDINAVIA / NORDICS
# ═══════════════════════════════════════════
{"name":"Hampus Jakobsson","bio":"Co-founder of Pale Blue Dot. Expert in climate and sustainability tech in Nordics.","location":"Malmo","country":"Sweden","twitter_url":"https://twitter.com/hajak","type":"vc","check_min":250000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["climate","saas","ai","marketplace","deep-tech"],"portfolio":[],"verified":True},
{"name":"Heidi Lindvall","bio":"Co-founder of Pale Blue Dot. Expert in climate tech early-stage investing.","location":"Malmo","country":"Sweden","twitter_url":"https://twitter.com/heidilindvall","type":"vc","check_min":250000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["climate","energy","saas","deep-tech"],"portfolio":[],"verified":True},
{"name":"Lasse Skaarup Andersen","bio":"Partner at Heartcore Capital. Expert in Danish and Scandinavian consumer tech.","location":"Copenhagen","country":"Denmark","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["consumer","saas","marketplace","fintech"],"portfolio":[],"verified":True},
{"name":"Louise Samet","bio":"Partner at Founders. Expert in Danish B2B SaaS startups.","location":"Copenhagen","country":"Denmark","type":"vc","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","b2b","marketplace","fintech"],"portfolio":[],"verified":True},
{"name":"Mads Jensen","bio":"Partner at Seed Capital. Expert in Nordic SaaS and marketplace investing.","location":"Copenhagen","country":"Denmark","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","marketplace","consumer","fintech"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════
# MORE CANADA VCs
# ═══════════════════════════════════════════
{"name":"Rob Antoniades","bio":"General Partner at Information Venture Partners. Expert in Canadian B2B fintech.","location":"Toronto","country":"Canada","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["fintech","saas","enterprise","marketplace"],"portfolio":[],"verified":True},
{"name":"Bruce Croxon","bio":"Co-founder of Lavalife. Dragon's Den investor. Expert in Canadian consumer and marketplace.","location":"Toronto","country":"Canada","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","fintech","saas"],"portfolio":["Lavalife","Round13 Capital"],"verified":True},
{"name":"John Ruffolo","bio":"Founder of Maverix Private Equity. Former CEO of OMERS Ventures. Expert in Canadian tech.","location":"Toronto","country":"Canada","twitter_url":"https://twitter.com/johnruffolo","type":"vc","check_min":2000000,"check_max":30000000,"stages":["series-a","series-b","growth"],"industries":["saas","marketplace","ai","fintech"],"portfolio":["Hootsuite","Shopify","D2L"],"verified":True},
{"name":"Roger Chabra","bio":"Partner at Inovia Capital. Expert in Canadian deep tech and enterprise.","location":"Montreal","country":"Canada","type":"vc","check_min":1000000,"check_max":20000000,"stages":["series-a","series-b"],"industries":["saas","ai","enterprise","developer-tools"],"portfolio":[],"verified":True},
{"name":"Patrick Pichette","bio":"General Partner at iNovia Capital. Former CFO of Google. Expert in scaling global tech.","location":"Montreal","country":"Canada","twitter_url":"https://twitter.com/patpichette","type":"vc","check_min":1000000,"check_max":20000000,"stages":["series-a","series-b","growth"],"industries":["saas","ai","enterprise","consumer","fintech"],"portfolio":["Lightspeed","Breather"],"verified":True},

# ═══════════════════════════════════════════
# ADDITIONAL EU ANGELS & VCs
# ═══════════════════════════════════════════
{"name":"Stefan Glaenzer","bio":"Founder of Passion Capital. Former CEO of Last.fm. Expert in UK seed investing.","location":"London","country":"UK","type":"vc","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","media"],"portfolio":["Transferwise","Songkick","Swiftkey"],"verified":True},
{"name":"Eileen Burbidge","bio":"Partner at Passion Capital. UK Government Fintech Envoy. Expert in UK tech and fintech.","location":"London","country":"UK","twitter_url":"https://twitter.com/eileentso","type":"vc","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["fintech","saas","consumer","marketplace"],"portfolio":["Transferwise","Monzo","FutureAdvisor"],"verified":True},
{"name":"Carlos Espinal","bio":"Managing Partner at Seedcamp. Expert in European pre-seed and seed investing.","location":"London","country":"UK","twitter_url":"https://twitter.com/cee","type":"vc","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","fintech","ai","developer-tools"],"portfolio":["Revolut","UiPath","Wise"],"verified":True},
{"name":"Reshma Sohoni","bio":"Co-founder of Seedcamp. Pioneer of European startup ecosystem. Expert in early-stage EU tech.","location":"London","country":"UK","twitter_url":"https://twitter.com/rsohoni","type":"vc","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","fintech","marketplace","consumer","developer-tools"],"portfolio":["Revolut","UiPath","Wise","Viz.ai"],"verified":True},
{"name":"Christoph Janz","bio":"Co-founder of Point Nine Capital. Expert in B2B SaaS. Writes influential SaaS content.","location":"Berlin","country":"Germany","twitter_url":"https://twitter.com/chrija","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","b2b","marketplace","fintech"],"portfolio":["Zendesk","Contentful","Clio","Typeform"],"verified":True},
{"name":"Nicolas Wittenborn","bio":"Co-founder of Adjacent. Expert in European consumer tech.","location":"Berlin","country":"Germany","twitter_url":"https://twitter.com/nwittenborn","type":"vc","check_min":250000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas","creator-economy"],"portfolio":[],"verified":True},
{"name":"Nico Goulet","bio":"Co-founder of Serena Capital. Expert in French and Southern European B2B SaaS.","location":"Paris","country":"France","type":"vc","check_min":500000,"check_max":8000000,"stages":["seed","series-a"],"industries":["saas","b2b","marketplace","fintech"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════
# MORE ANGELS - OPERATORS
# ═══════════════════════════════════════════
{"name":"Tristan Walker","bio":"Founder of Walker and Company Brands. Angel investor in consumer and underrepresented founders.","location":"Palo Alto, CA","country":"USA","twitter_url":"https://twitter.com/tristanwalker","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","e-commerce","health","marketplace"],"portfolio":["Walker and Company"],"verified":True},
{"name":"Jason Goldberg","bio":"Founder of Fab.com. Serial entrepreneur and angel investor in consumer and e-commerce.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/betashop","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","e-commerce","marketplace","saas"],"portfolio":["Fab.com"],"verified":True},
{"name":"Gokul Rajaram","bio":"Board member at DoorDash and Pinterest. Former Square and Facebook. Active angel.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/gokulr","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","developer-tools","ai"],"portfolio":[],"verified":True},
{"name":"Amir Shevat","bio":"Former Head of Developer Relations at Slack and Twitter. Angel in developer tools.","location":"Tel Aviv","country":"Israel","twitter_url":"https://twitter.com/ashevat","type":"angel","check_min":10000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["developer-tools","saas","ai","marketplace"],"portfolio":[],"verified":True},
{"name":"Hunter Walk","bio":"Co-founder of Homebrew VC. Former Google and YouTube PM. Expert in early-stage consumer.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/hunterwalk","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","future-of-work"],"portfolio":["Plaid","Chime","Cruise"],"verified":True},
{"name":"Satya Patel","bio":"Co-founder of Homebrew VC. Former VP Product at Twitter. Early-stage consumer expert.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/satyap","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","health"],"portfolio":["Plaid","Chime"],"verified":True},
{"name":"Joshua Kushner","bio":"Co-founder of Thrive Capital and Oscar Health. Expert in healthcare and consumer tech.","location":"New York, NY","country":"USA","type":"vc","check_min":5000000,"check_max":200000000,"stages":["series-a","series-b","growth"],"industries":["health","consumer","fintech","saas","marketplace"],"portfolio":["Instagram","Spotify","GitHub","Kickstarter","Oscar Health"],"verified":True},
{"name":"Ali Partovi","bio":"Co-founder of Code.org. Mentor at NEA. Early investor in Facebook, Zappos, Dropbox, airbnb.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/apartovi","type":"angel","check_min":100000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","edtech","marketplace","ai"],"portfolio":["Facebook","Zappos","Dropbox","Airbnb","Spotify"],"verified":True},
{"name":"Scott Banister","bio":"Co-founder of IronPort. Early investor in PayPal, Uber, SpaceX. Super angel.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":100000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","fintech","ai"],"portfolio":["PayPal","Uber","SpaceX","Lyft"],"verified":True},
{"name":"Owen Van Natta","bio":"Former COO of Facebook and MySpace. Angel investor in consumer social products.","location":"Menlo Park, CA","country":"USA","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["consumer","social","marketplace","saas"],"portfolio":["Facebook","MySpace"],"verified":True},
{"name":"Amr Awadallah","bio":"Co-founder of Cloudera (IPO $4B+). Active angel in enterprise data and AI.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/awadallah","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["data","ai","enterprise","saas","developer-tools"],"portfolio":["Cloudera","Vectara"],"verified":True},
{"name":"Dave Morin","bio":"Co-founder of Path. Former Facebook platform lead. Angel in consumer social and mobile.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/davemorin","type":"angel","check_min":50000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["consumer","social","mobile","saas","marketplace"],"portfolio":["Path","Branch"],"verified":True},
{"name":"Semil Shah","bio":"General Partner at Haystack Fund. One of the most connected angels in Silicon Valley.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/semil","type":"vc","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","ai","fintech"],"portfolio":["Instacart","DoorDash","Hashicorp","Figma"],"verified":True},
{"name":"Antonio Garcia Martinez","bio":"Author of Chaos Monkeys. Former Facebook PM. Angel in consumer and adtech.","location":"London","country":"UK","twitter_url":"https://twitter.com/antoniogm","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","adtech","saas","crypto"],"portfolio":[],"verified":True},
{"name":"Max Levchin","bio":"Co-founder of PayPal and Affirm. Active angel investor in fintech and consumer.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/mlevchin","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["fintech","consumer","ai","saas","marketplace"],"portfolio":["PayPal","Affirm","Yelp","Slide"],"verified":True},
{"name":"Peter Thiel","bio":"Co-founder of PayPal and Palantir. Founder of Founders Fund. Early investor in Facebook, LinkedIn.","location":"Miami, FL","country":"USA","twitter_url":"https://twitter.com/peterthiel","type":"angel","check_min":1000000,"check_max":100000000,"stages":["seed","series-a","series-b"],"industries":["ai","defense","crypto","fintech","deep-tech","consumer"],"portfolio":["Facebook","LinkedIn","Palantir","SpaceX","Airbnb"],"verified":True},
{"name":"Luke Nosek","bio":"Co-founder of PayPal and Founders Fund. Deep tech and defense investor.","location":"Austin, TX","country":"USA","type":"angel","check_min":1000000,"check_max":50000000,"stages":["seed","series-a"],"industries":["deep-tech","defense","ai","space","fintech"],"portfolio":["PayPal","SpaceX","Palantir"],"verified":True},
{"name":"Keith Rabois","bio":"Partner at Founders Fund. Former COO of Square. Prolific angel in fintech and marketplace.","location":"Miami, FL","country":"USA","twitter_url":"https://twitter.com/rabois","type":"angel","check_min":100000,"check_max":5000000,"stages":["pre-seed","seed","series-a"],"industries":["fintech","marketplace","real-estate","saas","consumer"],"portfolio":["Square","Yelp","Quora","Lyft","DoorDash","Opendoor"],"verified":True},
{"name":"Reid Hoffman","bio":"Co-founder of LinkedIn. Partner at Greylock. Most networked VC in Silicon Valley.","location":"Palo Alto, CA","country":"USA","twitter_url":"https://twitter.com/reidhoffman","type":"vc","check_min":500000,"check_max":20000000,"stages":["seed","series-a","series-b"],"industries":["saas","ai","consumer","marketplace","fintech"],"portfolio":["LinkedIn","Airbnb","Facebook","Zynga","Convex"],"verified":True},

# ═══════════════════════════════════════════
# MORE ECOSYSTEM ANGELS
# ═══════════════════════════════════════════
{"name":"Lars Dalgaard","bio":"General Partner at a16z. Former CEO of SuccessFactors (sold to SAP for $3.4B). HR SaaS expert.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":3000000,"check_max":100000000,"stages":["seed","series-a","series-b"],"industries":["saas","hr-tech","enterprise","ai"],"portfolio":["SuccessFactors","Zenefits"],"verified":True},
{"name":"Alex Kolicich","bio":"Co-founder of 8VC. Expert in frontier tech, data analytics, and life sciences.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":2000000,"check_max":30000000,"stages":["series-a","series-b"],"industries":["deep-tech","health","defense","data","ai"],"portfolio":[],"verified":True},
{"name":"Zach Weinberg","bio":"Co-founder of Flatiron Health (acquired by Roche for $1.9B). Angel in health AI.","location":"New York, NY","country":"USA","type":"angel","check_min":100000,"check_max":3000000,"stages":["seed","series-a"],"industries":["health","ai","saas","biotech"],"portfolio":["Flatiron Health"],"verified":True},
{"name":"Nat Turner","bio":"Co-founder of Flatiron Health. Angel investor in healthcare AI and enterprise SaaS.","location":"New York, NY","country":"USA","type":"angel","check_min":100000,"check_max":3000000,"stages":["seed","series-a"],"industries":["health","ai","enterprise","saas"],"portfolio":["Flatiron Health"],"verified":True},
{"name":"Stephanie Palmeri","bio":"Partner at Uncork Capital. Expert in early-stage consumer and B2B SaaS.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/stephaniepalm","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","health"],"portfolio":[],"verified":True},
{"name":"Jeff Clavier","bio":"Founder of Uncork Capital (formerly SoftTech VC). Veteran early-stage consumer VC.","location":"Palo Alto, CA","country":"USA","twitter_url":"https://twitter.com/jeff","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","developer-tools","fintech"],"portfolio":["Mint","SendGrid","FitBit","Eventbrite"],"verified":True},
{"name":"Manu Rekhi","bio":"Partner at Inventus Capital. Expert in Indian-American founders and enterprise SaaS.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","enterprise","marketplace","fintech"],"portfolio":[],"verified":True},
{"name":"Venky Ganesan","bio":"Managing Director at Menlo Ventures. Expert in cybersecurity and enterprise software.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/venkyganesan","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["security","saas","enterprise","ai","cloud"],"portfolio":["Chime","Carta","Pendo"],"verified":True},

]

# Deduplicate
seen = set()
UNIQUE = []
for inv in INVESTORS_BATCH5:
    key = inv["name"].lower().strip()
    if key not in seen:
        seen.add(key)
        UNIQUE.append(inv)

INVESTORS_BATCH5 = UNIQUE
print(f"[OK] Loaded {len(INVESTORS_BATCH5)} investors in batch 5")
