# -*- coding: utf-8 -*-
"""OpenAngels - Batch 10: Final 25 to cross 1000"""

INVESTORS_BATCH10 = [
{"name":"Laila Ahmadi","bio":"Investor at LocalGlobe. Expert in pre-seed European consumer and marketplace.","location":"London","country":"UK","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas","impact"],"portfolio":[],"verified":True},
{"name":"Jeff Ma","bio":"Co-founder of Citizen Sports. Angel investor in sports tech and consumer apps.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["sports","consumer","saas","marketplace"],"portfolio":[],"verified":True},
{"name":"Ali Yahya","bio":"General Partner at a16z Crypto. Expert in blockchain infrastructure and DeFi.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/ali01","type":"vc","check_min":1000000,"check_max":50000000,"stages":["seed","series-a"],"industries":["crypto","web3","defi","developer-tools","infrastructure"],"portfolio":[],"verified":True},
{"name":"James Joaquin","bio":"Co-founder of Obvious Ventures. Expert in sustainable consumer and climate tech.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/jamesjoaquin","type":"vc","check_min":1000000,"check_max":15000000,"stages":["seed","series-a"],"industries":["climate","health","consumer","saas","impact"],"portfolio":["Beyond Meat","Modern Fertility"],"verified":True},
{"name":"Tom Hulme","bio":"General Partner at GV (Google Ventures). Design thinker and consumer expert.","location":"London","country":"UK","twitter_url":"https://twitter.com/thulme","type":"vc","check_min":2000000,"check_max":30000000,"stages":["seed","series-a"],"industries":["consumer","design","saas","marketplace","health"],"portfolio":[],"verified":True},
{"name":"Rak Garg","bio":"Partner at Bain Capital Ventures. Expert in consumer and marketplace companies.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["consumer","marketplace","saas","fintech"],"portfolio":[],"verified":True},
{"name":"Scott Friend","bio":"Partner at Bain Capital Ventures. Expert in e-commerce and marketplace companies.","location":"Boston, MA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["e-commerce","marketplace","consumer","saas"],"portfolio":["Rent the Runway","Flatiron Health"],"verified":True},
{"name":"Enrique Salem","bio":"Former CEO of Symantec. Partner at Bain Capital Ventures. Cybersecurity expert.","location":"Palo Alto, CA","country":"USA","type":"vc","check_min":5000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["security","enterprise","saas","ai"],"portfolio":["Symantec"],"verified":True},
{"name":"Aaref Hilaly","bio":"Partner at Bain Capital Ventures. Former CEO of Clearwell Systems. Enterprise expert.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["enterprise","saas","ai","security","developer-tools"],"portfolio":[],"verified":True},
{"name":"Robert Hatta","bio":"Partner at Deep Dive Ventures. Expert in Japanese deep tech startups.","location":"Tokyo","country":"Japan","type":"vc","check_min":200000,"check_max":3000000,"stages":["seed","series-a"],"industries":["deep-tech","ai","saas","enterprise"],"portfolio":[],"verified":True},
{"name":"Jean de La Rochebrochard","bio":"Partner at Kima Ventures. Worlds most active seed fund, 100+ deals/year.","location":"Paris","country":"France","twitter_url":"https://twitter.com/_jean_b","type":"vc","check_min":150000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","consumer","fintech","ai","developer-tools"],"portfolio":["Algolia","Aircall","Spendesk"],"verified":True},
{"name":"Xavier Lorphelin","bio":"Co-founder of Kima Ventures. World's most prolific seed investor (100+ deals/year).","location":"Paris","country":"France","type":"vc","check_min":150000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","fintech","consumer","ai"],"portfolio":["Algolia","Aircall","Spendesk"],"verified":True},
{"name":"Cyril de Tournemire","bio":"Co-founder of Kima Ventures. Expert in French and global pre-seed startups.","location":"Paris","country":"France","type":"vc","check_min":150000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","consumer","fintech"],"portfolio":[],"verified":True},
{"name":"David Cramer","bio":"Co-founder of Sentry. Angel investor in developer tools and open source companies.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/zeeg","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["developer-tools","open-source","saas","infrastructure"],"portfolio":["Sentry"],"verified":True},
{"name":"Chris Jennings","bio":"Partner at Foresite Capital. Expert in biotech and life sciences investing.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":5000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["biotech","health","ai","genomics"],"portfolio":[],"verified":True},
{"name":"Santi Subotovsky","bio":"General Partner at Emergence Capital. Expert in cloud AI and enterprise SaaS.","location":"San Mateo, CA","country":"USA","twitter_url":"https://twitter.com/ssanto","type":"vc","check_min":3000000,"check_max":30000000,"stages":["series-a","series-b"],"industries":["saas","enterprise","ai","cloud"],"portfolio":["Veeva","Salesforce","Zoom"],"verified":True},
{"name":"Brian Feinstein","bio":"General Partner at Bessemer. Expert in marketplace and consumer businesses.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["marketplace","consumer","saas","fintech"],"portfolio":["Fiverr","Toast","Mindbody"],"verified":True},
{"name":"Nicolas Dessaigne","bio":"Co-founder of Algolia. Angel investor in developer tools and search infrastructure.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/dessaigne","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["developer-tools","saas","infrastructure","ai"],"portfolio":["Algolia"],"verified":True},
{"name":"Julien Lemoine","bio":"Co-founder of Algolia. Angel investor in French and US developer tooling startups.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["developer-tools","saas","api","infrastructure"],"portfolio":["Algolia"],"verified":True},
{"name":"Mike Preuss","bio":"Co-founder of Visible.vc. Angel investor in SaaS and startup tooling companies.","location":"Chicago, IL","country":"USA","twitter_url":"https://twitter.com/mikepreuss","type":"angel","check_min":10000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["saas","developer-tools","marketplace","b2b"],"portfolio":["Visible.vc"],"verified":True},
{"name":"Christoph Cemper","bio":"Founder of LinkResearchTools. Angel in SEO tech and European SaaS startups.","location":"Vienna","country":"Austria","type":"angel","check_min":10000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["saas","marketing-tech","developer-tools","marketplace"],"portfolio":[],"verified":False},
{"name":"Lukasz Gadowski","bio":"Co-founder of Spreadshirt. Partner at Team Europe. Expert in European marketplace.","location":"Berlin","country":"Germany","twitter_url":"https://twitter.com/lukaszgadowski","type":"vc","check_min":250000,"check_max":3000000,"stages":["seed","series-a"],"industries":["marketplace","consumer","saas","e-commerce"],"portfolio":["Spreadshirt","Delivery Hero","Wooga"],"verified":True},
{"name":"Verena Pausder","bio":"Founder of Fox & Sheep (acquired by Disney). Expert in German edtech and consumer.","location":"Berlin","country":"Germany","twitter_url":"https://twitter.com/verenapausder","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["edtech","consumer","gaming","saas"],"portfolio":["Fox and Sheep"],"verified":True},
{"name":"Juha Ruohonen","bio":"Partner at Maki.vc. Expert in Finnish and Nordic tech ecosystems.","location":"Helsinki","country":"Finland","type":"vc","check_min":200000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","fintech","ai","consumer"],"portfolio":[],"verified":True},
{"name":"Mato Peric","bio":"Partner at South Central Ventures. Expert in Croatian and Balkan tech startups.","location":"Zagreb","country":"Croatia","type":"vc","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["saas","fintech","marketplace","ai"],"portfolio":[],"verified":True},
]

seen = set()
UNIQUE = []
for inv in INVESTORS_BATCH10:
    key = inv["name"].lower().strip()
    if key not in seen:
        seen.add(key)
        UNIQUE.append(inv)
INVESTORS_BATCH10 = UNIQUE
print(f"[OK] Loaded {len(INVESTORS_BATCH10)} investors in batch 10")
