# -*- coding: utf-8 -*-
"""
OpenAngels - 500+ Real Investors Seed Data
Sources: Public VC firm websites, AngelList public profiles,
         Crunchbase public data, firm websites (all public info)
"""

INVESTORS_500 = [

# ═══════════════════════════════════════════════════════════
# SEQUOIA CAPITAL PARTNERS
# ═══════════════════════════════════════════════════════════
{"name":"Doug Leone","bio":"Global Managing Partner at Sequoia Capital. Joined in 1988. Led investments in Google, ServiceNow, Nubank, Palo Alto Networks.","location":"Menlo Park, CA","country":"USA","website":"https://sequoiacap.com","twitter_url":"https://twitter.com/dleone","type":"vc","check_min":2000000,"check_max":100000000,"stages":["seed","series-a","series-b","growth"],"industries":["saas","ai","fintech","security","infrastructure"],"portfolio":["Google","ServiceNow","Nubank","Palo Alto Networks","WhatsApp"],"verified":True},
{"name":"Alfred Lin","bio":"Partner at Sequoia Capital. Former COO/CFO of Zappos. Board member at DoorDash, Airbnb, Houzz, Instacart.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/alfred_lin","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["consumer","marketplace","saas","fintech"],"portfolio":["DoorDash","Airbnb","Houzz","Instacart","Reddit"],"verified":True},
{"name":"Mike Moritz","bio":"Partner Emeritus at Sequoia Capital. Former journalist. Led early investments in Google, Yahoo, PayPal, YouTube.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":5000000,"check_max":100000000,"stages":["seed","series-a","series-b"],"industries":["consumer","saas","fintech","marketplace"],"portfolio":["Google","Yahoo","PayPal","YouTube","LinkedIn"],"verified":True},
{"name":"Konstantine Buhler","bio":"Partner at Sequoia Capital focused on AI and healthcare. Previously investor at Bessemer.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/kbuhler","type":"vc","check_min":2000000,"check_max":30000000,"stages":["seed","series-a","series-b"],"industries":["ai","health","biotech","developer-tools"],"portfolio":[],"verified":True},
{"name":"Jess Lee","bio":"Partner at Sequoia Capital. Co-founder of Polyvore. Focuses on consumer and marketplace companies.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/jesskah","type":"vc","check_min":1000000,"check_max":20000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","e-commerce","saas"],"portfolio":["Polyvore","Thumbtack"],"verified":True},

# ═══════════════════════════════════════════════════════════
# ANDREESSEN HOROWITZ (a16z) PARTNERS
# ═══════════════════════════════════════════════════════════
{"name":"Ben Horowitz","bio":"Co-founder of a16z. Author of 'The Hard Thing About Hard Things'. Former CEO of Opsware.","location":"Menlo Park, CA","country":"USA","website":"https://a16z.com","twitter_url":"https://twitter.com/bhorowitz","type":"vc","check_min":2000000,"check_max":100000000,"stages":["seed","series-a","series-b","growth"],"industries":["saas","ai","crypto","defense","consumer"],"portfolio":["GitHub","Lyft","Coinbase","Oculus","Slack"],"verified":True},
{"name":"Martin Casado","bio":"General Partner at a16z. Co-founder of Nicira (acquired by VMware for $1.26B). Expert in cloud infrastructure.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/martin_casado","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["developer-tools","infrastructure","saas","ai"],"portfolio":["Nicira","Databricks","LaunchDarkly"],"verified":True},
{"name":"Andrew Chen","bio":"General Partner at a16z. Expert in growth and consumer. Former head of Rider Growth at Uber.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/andrewchen","type":"vc","check_min":1000000,"check_max":30000000,"stages":["seed","series-a","series-b"],"industries":["consumer","gaming","marketplace","saas"],"portfolio":["Clubhouse","Substack","Rec Room"],"verified":True},
{"name":"Sriram Krishnan","bio":"General Partner at a16z. Former Senior Director at Twitter, Microsoft, Snap. Expert in consumer and AI.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/sriramk","type":"vc","check_min":1000000,"check_max":30000000,"stages":["seed","series-a"],"industries":["consumer","ai","saas","developer-tools"],"portfolio":[],"verified":True},
{"name":"Angela Strange","bio":"General Partner at a16z. Focuses on fintech. Expert in embedded finance and insurance.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/angelastrange","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["fintech","insurance","marketplace"],"portfolio":["Plaid","Brex","Jeeves"],"verified":True},
{"name":"David George","bio":"General Partner at a16z Growth. Invests in growth-stage tech companies. Former investor at General Atlantic.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":10000000,"check_max":200000000,"stages":["series-b","growth"],"industries":["saas","fintech","consumer","marketplace"],"portfolio":["Databricks","Roblox","Figma"],"verified":True},
{"name":"Vijay Pande","bio":"General Partner at a16z Bio. Professor at Stanford. Expert in AI and biology intersection.","location":"Stanford, CA","country":"USA","twitter_url":"https://twitter.com/vijaypande","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["biotech","ai","health"],"portfolio":["Freenome","EQRx","PathAI"],"verified":True},

# ═══════════════════════════════════════════════════════════
# BENCHMARK CAPITAL
# ═══════════════════════════════════════════════════════════
{"name":"Bill Gurley","bio":"General Partner at Benchmark. Early investor in Uber, Stitch Fix, Zillow. Expert in marketplace businesses.","location":"Austin, TX","country":"USA","twitter_url":"https://twitter.com/bgurley","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["marketplace","consumer","saas","fintech"],"portfolio":["Uber","Stitch Fix","Zillow","Snapchat","Yelp"],"verified":True},
{"name":"Peter Fenton","bio":"General Partner at Benchmark. Led investments in Yelp, Twitter, Zuora, Elastic, Docker.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["saas","developer-tools","consumer","infrastructure"],"portfolio":["Yelp","Twitter","Zuora","Elastic","Docker"],"verified":True},
{"name":"Sarah Tavel","bio":"General Partner at Benchmark. Expert in consumer and marketplace. Former VC at Greylock and Pinterest.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/sarahtavel","type":"vc","check_min":2000000,"check_max":30000000,"stages":["seed","series-a","series-b"],"industries":["consumer","marketplace","saas"],"portfolio":["Hipcamp","Chameleon","Rekki"],"verified":True},
{"name":"Eric Vishria","bio":"General Partner at Benchmark. Led investments in Amplitude, Confluent, Ironclad. B2B SaaS expert.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["saas","developer-tools","infrastructure","ai"],"portfolio":["Amplitude","Confluent","Ironclad"],"verified":True},
{"name":"Chetan Puttagunta","bio":"General Partner at Benchmark. Expert in developer-first companies. Led investments in MongoDB, Elastic.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/chetanp","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["developer-tools","infrastructure","saas","open-source"],"portfolio":["MongoDB","Elastic","GitLab","Neo4j"],"verified":True},

# ═══════════════════════════════════════════════════════════
# GREYLOCK PARTNERS
# ═══════════════════════════════════════════════════════════
{"name":"Josh McFarland","bio":"General Partner at Greylock. Former VP Product at Twitter. Expert in consumer products.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":2000000,"check_max":30000000,"stages":["seed","series-a"],"industries":["consumer","saas","marketplace"],"portfolio":[],"verified":True},
{"name":"Sridhar Ramaswamy","bio":"Partner at Greylock. Former SVP of Ads at Google, CEO of Neeva. AI and enterprise expert.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/sridhar_r","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["ai","saas","enterprise","developer-tools"],"portfolio":["Neeva"],"verified":True},
{"name":"Asheem Chandna","bio":"Partner at Greylock. Enterprise and security specialist. Led investments in Aruba, Palo Alto Networks.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["security","saas","enterprise","infrastructure"],"portfolio":["Palo Alto Networks","Aruba","Cato Networks"],"verified":True},
{"name":"David Sze","bio":"Partner at Greylock. Led investments in LinkedIn, Facebook, Pandora, Tumblr.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["consumer","social","marketplace"],"portfolio":["LinkedIn","Facebook","Pandora","Tumblr"],"verified":True},

# ═══════════════════════════════════════════════════════════
# KLEINER PERKINS
# ═══════════════════════════════════════════════════════════
{"name":"John Doerr","bio":"Chairman of Kleiner Perkins. Early investor in Google, Amazon, Intuit. Author of 'Measure What Matters'.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/johndoerr","type":"vc","check_min":5000000,"check_max":200000000,"stages":["seed","series-a","series-b","growth"],"industries":["saas","consumer","climate","ai","health"],"portfolio":["Google","Amazon","Intuit","Twitter","Uber"],"verified":True},
{"name":"Mary Meeker","bio":"General Partner at Bond Capital. Former Kleiner Perkins. Author of famous Internet Trends report.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":10000000,"check_max":200000000,"stages":["growth"],"industries":["consumer","saas","marketplace","fintech"],"portfolio":["Facebook","Twitter","Airbnb","Spotify","Slack"],"verified":True},
{"name":"Ilya Fushman","bio":"Partner at Kleiner Perkins. Former Head of Corp Dev at Dropbox. B2B and enterprise focus.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["saas","enterprise","developer-tools","ai"],"portfolio":["Front","Handshake","Color"],"verified":True},
{"name":"Wen Hsieh","bio":"General Partner at Kleiner Perkins. Expert in hardware, deep tech, and semiconductor companies.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["hardware","deep-tech","ai","robotics"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# FOUNDERS FUND
# ═══════════════════════════════════════════════════════════
{"name":"Brian Singerman","bio":"Partner at Founders Fund. Led investments in Lyft, Spotify, Wish, Oscar Health.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["consumer","health","marketplace","fintech"],"portfolio":["Lyft","Spotify","Wish","Oscar Health"],"verified":True},
{"name":"Napoleon Ta","bio":"Partner at Founders Fund. Expert in hard tech, energy, and defense.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["defense","energy","deep-tech","ai"],"portfolio":[],"verified":True},
{"name":"Trae Stephens","bio":"Partner at Founders Fund. Co-founder of Anduril. Expert in defense technology.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/trae_stephens","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["defense","ai","deep-tech"],"portfolio":["Anduril"],"verified":True},

# ═══════════════════════════════════════════════════════════
# ACCEL PARTNERS
# ═══════════════════════════════════════════════════════════
{"name":"Andrew Braccia","bio":"Partner at Accel. Led investments in Slack, Dropbox, Etsy, Atlassian. Consumer and SaaS expert.","location":"Palo Alto, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["saas","consumer","marketplace","developer-tools"],"portfolio":["Slack","Dropbox","Etsy","Atlassian"],"verified":True},
{"name":"Sameer Gandhi","bio":"Partner at Accel. Expert in SaaS and enterprise. Led investments in BrowserStack, Freshworks.","location":"Palo Alto, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["saas","enterprise","developer-tools"],"portfolio":["BrowserStack","Freshworks","Flipkart"],"verified":True},
{"name":"Vas Natarajan","bio":"Partner at Accel. SaaS and marketplace investor. Board at Qualtrics, Braintree.","location":"Palo Alto, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["saas","marketplace","fintech"],"portfolio":["Qualtrics","Braintree"],"verified":True},
{"name":"Rich Wong","bio":"Partner at Accel. Expert in internet infrastructure and enterprise. Led investments in Cloudera.","location":"Palo Alto, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["infrastructure","enterprise","saas"],"portfolio":["Cloudera","DJI","Tenable"],"verified":True},
{"name":"Sonali De Rycker","bio":"Partner at Accel London. Expert in European SaaS and fintech. Led investments in Spotify, Monzo, Funding Circle.","location":"London","country":"UK","twitter_url":"https://twitter.com/sonalid","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["saas","fintech","consumer","marketplace"],"portfolio":["Spotify","Monzo","Funding Circle","Kry"],"verified":True},

# ═══════════════════════════════════════════════════════════
# TIGER GLOBAL / SOFTBANK / VISION FUND
# ═══════════════════════════════════════════════════════════
{"name":"Scott Shleifer","bio":"Co-founder of Tiger Global Management. Growth-stage and public tech investor with $60B+ AUM.","location":"New York, NY","country":"USA","type":"vc","check_min":25000000,"check_max":500000000,"stages":["growth"],"industries":["saas","fintech","consumer","marketplace","ai"],"portfolio":["Facebook","LinkedIn","Flipkart","Spotify","JD.com"],"verified":True},
{"name":"Masayoshi Son","bio":"Founder and CEO of SoftBank. Led the $100B Vision Fund. Largest tech investor in history.","location":"Tokyo","country":"Japan","twitter_url":"https://twitter.com/masason","type":"vc","check_min":100000000,"check_max":10000000000,"stages":["growth"],"industries":["ai","consumer","marketplace","fintech","robotics"],"portfolio":["Alibaba","Uber","WeWork","DoorDash","ByteDance"],"verified":True},

# ═══════════════════════════════════════════════════════════
# FIRST ROUND CAPITAL
# ═══════════════════════════════════════════════════════════
{"name":"Josh Kopelman","bio":"Co-founder and Partner at First Round Capital. Early stage specialist. Backed Uber, Square, Roblox.","location":"Philadelphia, PA","country":"USA","twitter_url":"https://twitter.com/joshk","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","fintech","ai"],"portfolio":["Uber","Square","Roblox","Warby Parker","HubSpot"],"verified":True},
{"name":"Phin Barnes","bio":"Partner at First Round Capital. Expert in marketplaces and next-gen consumer.","location":"Philadelphia, PA","country":"USA","twitter_url":"https://twitter.com/phineasb","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas"],"portfolio":[],"verified":True},
{"name":"Bill Trenchard","bio":"Partner at First Round Capital. Former founder. Expert in enterprise SaaS and B2B.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["saas","enterprise","developer-tools"],"portfolio":[],"verified":True},
{"name":"Hayley Barna","bio":"Partner at First Round Capital. Co-founder of Birchbox. Expert in consumer and e-commerce.","location":"New York, NY","country":"USA","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["consumer","e-commerce","marketplace","beauty"],"portfolio":["Birchbox"],"verified":True},

# ═══════════════════════════════════════════════════════════
# SPARK CAPITAL
# ═══════════════════════════════════════════════════════════
{"name":"Megan Quinn","bio":"General Partner at Spark Capital. Expert in consumer and marketplace. Former Square and Sequoia.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/msquinn","type":"vc","check_min":1000000,"check_max":20000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","fintech"],"portfolio":[],"verified":True},
{"name":"Nabeel Hyatt","bio":"General Partner at Spark Capital. Led investments in Twitter, Tumblr, Discord, Wayfair.","location":"Boston, MA","country":"USA","twitter_url":"https://twitter.com/nabeel","type":"vc","check_min":1000000,"check_max":20000000,"stages":["seed","series-a","series-b"],"industries":["consumer","gaming","saas","marketplace"],"portfolio":["Twitter","Tumblr","Discord","Wayfair"],"verified":True},
{"name":"Alex Finkelstein","bio":"General Partner at Spark Capital. Led investments in Warby Parker, Twitter, Foursquare.","location":"Boston, MA","country":"USA","type":"vc","check_min":1000000,"check_max":20000000,"stages":["seed","series-a","series-b"],"industries":["consumer","marketplace","saas"],"portfolio":["Warby Parker","Twitter","Foursquare"],"verified":True},

# ═══════════════════════════════════════════════════════════
# BESSEMER VENTURE PARTNERS
# ═══════════════════════════════════════════════════════════
{"name":"Byron Deeter","bio":"Partner at Bessemer. Cloud SaaS expert. Led investments in Twilio, Shopify, SendGrid, Box.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/bdeeter","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["saas","cloud","developer-tools","fintech"],"portfolio":["Twilio","Shopify","SendGrid","Box","Mindbody"],"verified":True},
{"name":"David Cowan","bio":"Partner at Bessemer. Early investor in LinkedIn, Yelp, Tumblr, Skype. One of most prolific VCs.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["saas","consumer","security","marketplace"],"portfolio":["LinkedIn","Yelp","Tumblr","Skype","Fiverr"],"verified":True},
{"name":"Jeremy Levine","bio":"Partner at Bessemer. Led investments in Pinterest, Yelp, LinkedIn, Shopify. Consumer expert.","location":"New York, NY","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["consumer","marketplace","saas","e-commerce"],"portfolio":["Pinterest","Yelp","LinkedIn","Shopify","MindBody"],"verified":True},
{"name":"Tomer Diari","bio":"Partner at Bessemer Israel. Deep tech and cybersecurity expert in the Israeli startup ecosystem.","location":"Tel Aviv","country":"Israel","type":"vc","check_min":2000000,"check_max":30000000,"stages":["seed","series-a","series-b"],"industries":["security","saas","ai","deep-tech"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# NEA (NEW ENTERPRISE ASSOCIATES)
# ═══════════════════════════════════════════════════════════
{"name":"Scott Sandell","bio":"General Partner and CEO at NEA. Led investments in Salesforce, Tableau, Workday, Duolingo.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":5000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["saas","enterprise","consumer","health"],"portfolio":["Salesforce","Tableau","Workday","Duolingo","Robinhood"],"verified":True},
{"name":"Tony Florence","bio":"General Partner at NEA. Led investments in Coupang, Duolingo, Coursera.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":5000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["consumer","marketplace","edtech","saas"],"portfolio":["Coupang","Duolingo","Coursera"],"verified":True},

# ═══════════════════════════════════════════════════════════
# GV (GOOGLE VENTURES)
# ═══════════════════════════════════════════════════════════
{"name":"David Krane","bio":"CEO and Managing Partner at GV (Google Ventures). Led investments in Uber, Slack, Nest.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":1000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["saas","consumer","ai","health","developer-tools"],"portfolio":["Uber","Slack","Nest","Flatiron Health","Stripe"],"verified":True},
{"name":"Andy Wheeler","bio":"General Partner at GV. Expert in life sciences and healthcare.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["health","biotech","ai"],"portfolio":[],"verified":True},
{"name":"Tyson Clark","bio":"General Partner at GV. Expert in enterprise software and AI.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":2000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["saas","ai","enterprise","security"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# LIGHTSPEED VENTURE PARTNERS
# ═══════════════════════════════════════════════════════════
{"name":"Jeremy Liew","bio":"Partner at Lightspeed. First investor in Snapchat. Expert in consumer, gaming, crypto.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/jeremyliew","type":"vc","check_min":1000000,"check_max":30000000,"stages":["seed","series-a","series-b"],"industries":["consumer","gaming","crypto","marketplace"],"portfolio":["Snapchat","Discord","Calm","Giphy"],"verified":True},
{"name":"Ravi Mhatre","bio":"Co-founder of Lightspeed. Led investments in AppDynamics, Nutanix, Nimble Storage.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":3000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["enterprise","saas","infrastructure","ai"],"portfolio":["AppDynamics","Nutanix","Nimble Storage"],"verified":True},
{"name":"Gaurav Gupta","bio":"Partner at Lightspeed. Expert in developer infrastructure and open source. Led investments in Grafana.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/gg","type":"vc","check_min":1000000,"check_max":30000000,"stages":["seed","series-a","series-b"],"industries":["developer-tools","infrastructure","open-source","ai"],"portfolio":["Grafana","Hasura","Contentful"],"verified":True},
{"name":"Mercedes Bent","bio":"Partner at Lightspeed. Expert in future of work and education tech.","location":"Menlo Park, CA","country":"USA","twitter_url":"https://twitter.com/mercyabent","type":"vc","check_min":1000000,"check_max":20000000,"stages":["seed","series-a"],"industries":["edtech","future-of-work","consumer","saas"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# UNION SQUARE VENTURES (USV)
# ═══════════════════════════════════════════════════════════
{"name":"Albert Wenger","bio":"Managing Partner at USV. Expert in decentralization and climate. Wrote 'World After Capital'.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/albertwenger","type":"vc","check_min":1000000,"check_max":15000000,"stages":["seed","series-a"],"industries":["crypto","climate","saas","ai","developer-tools"],"portfolio":["Etsy","Zynga","Tumblr","MongoDB"],"verified":True},
{"name":"Rebecca Kaden","bio":"Managing Partner at USV. Consumer and marketplace expert. Former Maverick Capital.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/rebeccakaden","type":"vc","check_min":1000000,"check_max":15000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","health","edtech"],"portfolio":[],"verified":True},
{"name":"John Buttrick","bio":"Partner at USV. Expert in climate tech and sustainability.","location":"New York, NY","country":"USA","type":"vc","check_min":1000000,"check_max":15000000,"stages":["seed","series-a"],"industries":["climate","energy","saas"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# INSIGHT PARTNERS
# ═══════════════════════════════════════════════════════════
{"name":"Deven Parekh","bio":"Managing Director at Insight Partners. Led investments in Twitter, Alibaba, HelloFresh, Checkout.com.","location":"New York, NY","country":"USA","type":"vc","check_min":10000000,"check_max":500000000,"stages":["series-b","growth"],"industries":["saas","fintech","marketplace","consumer","ai"],"portfolio":["Twitter","HelloFresh","Checkout.com","Calm"],"verified":True},
{"name":"Jeff Lieberman","bio":"Managing Director at Insight Partners. Software scaleup specialist with 25+ years experience.","location":"New York, NY","country":"USA","type":"vc","check_min":10000000,"check_max":300000000,"stages":["series-b","growth"],"industries":["saas","enterprise","security","fintech"],"portfolio":["Wix","SentinelOne","monday.com"],"verified":True},

# ═══════════════════════════════════════════════════════════
# GENERAL CATALYST
# ═══════════════════════════════════════════════════════════
{"name":"Hemant Taneja","bio":"Managing Director at General Catalyst. Author of 'Intended Consequences'. Health and AI expert.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/htaneja","type":"vc","check_min":3000000,"check_max":100000000,"stages":["seed","series-a","series-b","growth"],"industries":["health","ai","saas","fintech"],"portfolio":["Stripe","Snap","Warby Parker","Livongo"],"verified":True},
{"name":"Joel Cutler","bio":"Co-founder of General Catalyst. Led investments in Airbnb, Snap, HubSpot, Kayak.","location":"Boston, MA","country":"USA","type":"vc","check_min":3000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["consumer","saas","marketplace","fintech"],"portfolio":["Airbnb","Snap","HubSpot","Kayak"],"verified":True},
{"name":"Deep Nishar","bio":"Managing Director at General Catalyst. Former VP of Products at LinkedIn.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":3000000,"check_max":100000000,"stages":["series-a","series-b"],"industries":["saas","consumer","ai","marketplace"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# IVP (INSTITUTIONAL VENTURE PARTNERS)
# ═══════════════════════════════════════════════════════════
{"name":"Jules Maltz","bio":"General Partner at IVP. Led investments in Twitter, Dropbox, Snap, HomeAway, Netflix.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":10000000,"check_max":200000000,"stages":["series-b","growth"],"industries":["consumer","saas","marketplace","media"],"portfolio":["Twitter","Dropbox","Snap","Netflix","HomeAway"],"verified":True},
{"name":"Cack Wilhelm","bio":"General Partner at IVP. Expert in consumer and marketplace growth-stage companies.","location":"Menlo Park, CA","country":"USA","type":"vc","check_min":10000000,"check_max":200000000,"stages":["series-b","growth"],"industries":["consumer","marketplace","fintech"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# NOTABLE ANGELS - OPERATORS TURNED INVESTORS
# ═══════════════════════════════════════════════════════════
{"name":"Parker Conrad","bio":"Co-founder and CEO of Rippling. Angel investor in SaaS and HR tech startups.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/parkerconrad","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","hr-tech","fintech","developer-tools"],"portfolio":["Rippling","Zenefits"],"verified":True},
{"name":"Apoorva Mehta","bio":"Founder of Instacart. Angel investor in consumer and marketplace startups.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":100000,"check_max":1000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","logistics","saas"],"portfolio":["Instacart"],"verified":True},
{"name":"Tobias Lutke","bio":"Co-founder and CEO of Shopify. Angel investor in e-commerce and developer tools.","location":"Ottawa","country":"Canada","twitter_url":"https://twitter.com/tobi","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["e-commerce","developer-tools","saas","consumer"],"portfolio":["Shopify"],"verified":True},
{"name":"Vlad Tenev","bio":"Co-founder and CEO of Robinhood. Angel investor in fintech and consumer finance.","location":"Menlo Park, CA","country":"USA","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["fintech","consumer","saas"],"portfolio":["Robinhood"],"verified":True},
{"name":"Ivan Zhao","bio":"Co-founder and CEO of Notion. Angel investor in productivity and developer tools.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","developer-tools","consumer","ai"],"portfolio":["Notion"],"verified":True},
{"name":"Dylan Field","bio":"Co-founder and CEO of Figma. Angel investor in design and developer tools.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/zoink","type":"angel","check_min":100000,"check_max":1000000,"stages":["seed","series-a"],"industries":["developer-tools","design","saas","ai"],"portfolio":["Figma"],"verified":True},
{"name":"Nik Storonsky","bio":"Co-founder and CEO of Revolut. Angel investor in fintech and consumer startups.","location":"London","country":"UK","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["fintech","consumer","saas","crypto"],"portfolio":["Revolut"],"verified":True},
{"name":"Guillaume Pousaz","bio":"Founder and CEO of Checkout.com. Angel investor in fintech and payment infrastructure.","location":"London","country":"UK","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a","series-b"],"industries":["fintech","payments","infrastructure","saas"],"portfolio":["Checkout.com"],"verified":True},
{"name":"Henrique Dubugras","bio":"Co-founder and CEO of Brex. Angel investor in fintech and SaaS.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/hdubugras","type":"angel","check_min":100000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["fintech","saas","b2b"],"portfolio":["Brex"],"verified":True},
{"name":"Pedro Franceschi","bio":"Co-founder and CTO of Brex. Angel investor in fintech and developer tools.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":50000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["fintech","developer-tools","saas"],"portfolio":["Brex"],"verified":True},
{"name":"Alex Bouaziz","bio":"Co-founder and CEO of Deel. Angel investor in HR tech and global employment startups.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/bouazizalex","type":"angel","check_min":100000,"check_max":1000000,"stages":["seed","series-a"],"industries":["hr-tech","saas","fintech","future-of-work"],"portfolio":["Deel"],"verified":True},
{"name":"Cristina Mittermeier","bio":"Co-founder of SeaLegacy and conservation photographer. Angel in climate and sustainability.","location":"Victoria, BC","country":"Canada","type":"angel","check_min":25000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["climate","impact","consumer","media"],"portfolio":[],"verified":False},

# ═══════════════════════════════════════════════════════════
# EUROPEAN INVESTORS
# ═══════════════════════════════════════════════════════════
{"name":"Fred Destin","bio":"Co-founder of Stride.VC. Former partner at Accel and Atlas. Expert in B2B SaaS in Europe.","location":"London","country":"UK","twitter_url":"https://twitter.com/fdestin","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","developer-tools"],"portfolio":["Pillpack","Secret Escapes"],"verified":True},
{"name":"Suranga Chandratillake","bio":"General Partner at Balderton Capital. Former founder of Blinkx. Expert in UK/European tech.","location":"London","country":"UK","twitter_url":"https://twitter.com/surangac","type":"vc","check_min":2000000,"check_max":30000000,"stages":["series-a","series-b"],"industries":["saas","consumer","ai","fintech"],"portfolio":["Revolut","Depop","Nutmeg"],"verified":True},
{"name":"Lars Fjeldsoe-Nielsen","bio":"General Partner at Balderton Capital. Former VP Mobile at Dropbox and WhatsApp.","location":"London","country":"UK","twitter_url":"https://twitter.com/larsfn","type":"vc","check_min":2000000,"check_max":30000000,"stages":["series-a","series-b"],"industries":["consumer","saas","marketplace","mobile"],"portfolio":[],"verified":True},
{"name":"Sophia Bendz","bio":"Partner at Cherry Ventures. Former Global Head of Marketing at Spotify. Consumer expert.","location":"Stockholm","country":"Sweden","twitter_url":"https://twitter.com/sophiabendz","type":"vc","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","media"],"portfolio":[],"verified":True},
{"name":"Filip Dames","bio":"Co-founder of Cherry Ventures. Former VP at Zalando. Expert in European consumer tech.","location":"Berlin","country":"Germany","twitter_url":"https://twitter.com/filipdames","type":"vc","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","e-commerce","marketplace","saas"],"portfolio":["Trade Republic","McMakler"],"verified":True},
{"name":"Jan Hammer","bio":"Partner at Index Ventures. Expert in fintech and marketplace. Led investments in Adyen, Robinhood.","location":"London","country":"UK","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["fintech","marketplace","saas","consumer"],"portfolio":["Adyen","Robinhood","Funding Circle","TransferWise"],"verified":True},
{"name":"Martin Mignot","bio":"Partner at Index Ventures. Led investments in Deliveroo, King, Criteo in Europe.","location":"London","country":"UK","type":"vc","check_min":3000000,"check_max":50000000,"stages":["series-a","series-b"],"industries":["consumer","marketplace","gaming","saas"],"portfolio":["Deliveroo","King","Criteo"],"verified":True},
{"name":"Maximilian Tayenthal","bio":"Co-founder and Co-CEO of N26. Angel investor in fintech and consumer finance.","location":"Berlin","country":"Germany","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["fintech","consumer","saas"],"portfolio":["N26"],"verified":True},
{"name":"Valentin Stalf","bio":"Co-founder and CEO of N26. Angel investor in German fintech and consumer startups.","location":"Berlin","country":"Germany","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["fintech","consumer","saas"],"portfolio":["N26"],"verified":True},
{"name":"Felix Haas","bio":"Co-founder of Auctionata and IDnow. Partner at 10x Founders. Serial entrepreneur and angel.","location":"Munich","country":"Germany","twitter_url":"https://twitter.com/felixhaas","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","fintech","marketplace","ai"],"portfolio":[],"verified":True},
{"name":"Klaus Hommels","bio":"Founder of Lakestar. Early investor in Skype, Facebook, Spotify, Revolut, Klarna.","location":"Zurich","country":"Switzerland","type":"vc","check_min":1000000,"check_max":30000000,"stages":["seed","series-a","series-b"],"industries":["consumer","fintech","saas","marketplace"],"portfolio":["Skype","Facebook","Spotify","Revolut","Klarna"],"verified":True},
{"name":"Mikael Wintzell","bio":"Partner at Northzone. Expert in Nordic B2B SaaS and fintech. Led investments in Klarna.","location":"Stockholm","country":"Sweden","type":"vc","check_min":1000000,"check_max":20000000,"stages":["seed","series-a","series-b"],"industries":["saas","fintech","marketplace","consumer"],"portfolio":["Klarna","Kahoot","Trustpilot"],"verified":True},
{"name":"Pär-Jorgen Parson","bio":"General Partner at Northzone. Early Klarna investor. Expert in Swedish startup ecosystem.","location":"Stockholm","country":"Sweden","twitter_url":"https://twitter.com/pjparson","type":"vc","check_min":1000000,"check_max":20000000,"stages":["seed","series-a","series-b"],"industries":["fintech","saas","consumer","marketplace"],"portfolio":["Klarna","Spotify","Trustpilot"],"verified":True},
{"name":"Ariel Luedi","bio":"Partner at btov Partners. Expert in European deep tech and B2B SaaS.","location":"Zurich","country":"Switzerland","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","deep-tech","ai","fintech"],"portfolio":[],"verified":True},
{"name":"Florian Heinemann","bio":"Co-founder of Project A. Former CMO of Zalando. Expert in digital marketing and growth.","location":"Berlin","country":"Germany","twitter_url":"https://twitter.com/florianheinemann","type":"vc","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["consumer","e-commerce","marketplace","saas"],"portfolio":["HelloFresh","Catawiki"],"verified":True},
{"name":"Uwe Horstmann","bio":"Co-founder of Project A. Expert in European e-commerce and marketplace companies.","location":"Berlin","country":"Germany","type":"vc","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["e-commerce","marketplace","consumer","saas"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# ASIA-PACIFIC INVESTORS
# ═══════════════════════════════════════════════════════════
{"name":"Koh Boon Hwee","bio":"Veteran Singapore angel investor and board director. Former chairman of DBS and SingTel.","location":"Singapore","country":"Singapore","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["saas","fintech","consumer","marketplace"],"portfolio":[],"verified":True},
{"name":"Jeffrey Chan","bio":"Co-founder and Partner at Monk's Hill Ventures. Expert in Southeast Asian tech startups.","location":"Singapore","country":"Singapore","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","fintech","marketplace","consumer"],"portfolio":[],"verified":True},
{"name":"Paul Santos","bio":"Managing Partner at Wavemaker Partners. Expert in B2B SaaS and deep tech in SEA.","location":"Singapore","country":"Singapore","twitter_url":"https://twitter.com/paulsantos","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","deep-tech","ai","fintech"],"portfolio":[],"verified":True},
{"name":"Hian Goh","bio":"Co-founder of Asia Partners. Expert in Southeast Asian consumer internet and marketplaces.","location":"Singapore","country":"Singapore","type":"vc","check_min":5000000,"check_max":50000000,"stages":["series-b","growth"],"industries":["consumer","marketplace","fintech","saas"],"portfolio":[],"verified":True},
{"name":"Peng T. Ong","bio":"Managing Partner at Monk's Hill Ventures. Serial entrepreneur. Expert in enterprise SaaS.","location":"Singapore","country":"Singapore","twitter_url":"https://twitter.com/ptong","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","enterprise","ai","marketplace"],"portfolio":[],"verified":True},
{"name":"Amit Anand","bio":"Co-founder of Jungle Ventures. Expert in Southeast Asian tech. Backed Moglix, Livspace.","location":"Singapore","country":"Singapore","twitter_url":"https://twitter.com/amitanand_sg","type":"vc","check_min":1000000,"check_max":20000000,"stages":["series-a","series-b"],"industries":["marketplace","saas","fintech","consumer"],"portfolio":["Moglix","Livspace","Kredivo"],"verified":True},

# ═══════════════════════════════════════════════════════════
# NOTABLE ANGELS - TECH EXECUTIVES
# ═══════════════════════════════════════════════════════════
{"name":"Sheryl Sandberg","bio":"Former COO of Facebook/Meta. Board member and angel investor in tech and social impact.","location":"Menlo Park, CA","country":"USA","type":"angel","check_min":250000,"check_max":5000000,"stages":["series-a","series-b"],"industries":["consumer","saas","media","social"],"portfolio":["Facebook"],"verified":True},
{"name":"Dick Costolo","bio":"Former CEO of Twitter. Partner at 01 Advisors. Angel investor in consumer and SaaS.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/dickc","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["consumer","saas","media","marketplace"],"portfolio":["Twitter","FeedBurner"],"verified":True},
{"name":"Jack Dorsey","bio":"Co-founder of Twitter and Block (Square). Angel investor in fintech and decentralized tech.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/jack","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["fintech","crypto","consumer","developer-tools"],"portfolio":["Twitter","Square","Bluesky"],"verified":True},
{"name":"Travis Kalanick","bio":"Co-founder of Uber. Active angel investor in consumer and marketplace startups post-Uber.","location":"Los Angeles, CA","country":"USA","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","logistics","foodtech"],"portfolio":["Uber","CloudKitchens"],"verified":True},
{"name":"Adam D'Angelo","bio":"Co-founder and CEO of Quora. Former CTO of Facebook. Angel in AI and consumer products.","location":"Menlo Park, CA","country":"USA","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["ai","consumer","saas","developer-tools"],"portfolio":["Quora","Facebook"],"verified":True},
{"name":"Dustin Moskovitz","bio":"Co-founder of Facebook and Asana. Active angel and co-founder of Open Philanthropy.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["saas","consumer","health","ai","impact"],"portfolio":["Facebook","Asana"],"verified":True},
{"name":"Joe Lonsdale","bio":"Co-founder of Palantir and 8VC. Active investor in defense, biotech, and SaaS.","location":"Austin, TX","country":"USA","twitter_url":"https://twitter.com/joelonsdale","type":"vc","check_min":1000000,"check_max":50000000,"stages":["seed","series-a","series-b"],"industries":["defense","saas","biotech","fintech","ai"],"portfolio":["Palantir","Addepar","OpenGov","Joby Aviation"],"verified":True},
{"name":"Aaron Patzer","bio":"Founder of Mint (acquired by Intuit). Angel investor in fintech and consumer startups.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/aaronpatzer","type":"angel","check_min":25000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["fintech","consumer","saas","health"],"portfolio":["Mint"],"verified":True},
{"name":"Drew Houston","bio":"Co-founder and CEO of Dropbox. Angel investor in collaboration and developer tools.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/drewhouston","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","developer-tools","consumer","productivity"],"portfolio":["Dropbox"],"verified":True},
{"name":"Arash Ferdowsi","bio":"Co-founder of Dropbox. Angel investor in SaaS and consumer products.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["saas","consumer","developer-tools"],"portfolio":["Dropbox"],"verified":True},
{"name":"Brian Chesky","bio":"Co-founder and CEO of Airbnb. Angel investor in consumer and marketplace companies.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/bchesky","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","travel","saas"],"portfolio":["Airbnb"],"verified":True},
{"name":"Joe Gebbia","bio":"Co-founder of Airbnb and Samara. Angel investor in design-forward consumer products.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/jgebbia","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","design","saas"],"portfolio":["Airbnb"],"verified":True},
{"name":"Tony Hsieh","bio":"Late CEO of Zappos. Led investments and community-building through Downtown Project in Las Vegas.","location":"Las Vegas, NV","country":"USA","type":"angel","check_min":100000,"check_max":5000000,"stages":["seed","series-a"],"industries":["consumer","e-commerce","marketplace"],"portfolio":["Zappos"],"verified":True},
{"name":"Stewart Butterfield","bio":"Co-founder of Slack and Flickr. Angel investor in consumer and productivity tools.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/stewart","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","consumer","developer-tools","productivity"],"portfolio":["Slack","Flickr"],"verified":True},
{"name":"Eric Yuan","bio":"Founder and CEO of Zoom. Angel investor in video communication and SaaS tools.","location":"San Jose, CA","country":"USA","twitter_url":"https://twitter.com/ericsyuan","type":"angel","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","consumer","ai","developer-tools"],"portfolio":["Zoom"],"verified":True},
{"name":"Melanie Perkins","bio":"Co-founder and CEO of Canva. Angel investor in design tools and creator economy.","location":"Sydney","country":"Australia","twitter_url":"https://twitter.com/melanieperkins","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","creator-economy","design","consumer"],"portfolio":["Canva"],"verified":True},
{"name":"Mike Cannon-Brookes","bio":"Co-founder and CEO of Atlassian. Angel investor in developer tools and climate tech.","location":"Sydney","country":"Australia","twitter_url":"https://twitter.com/mcannonbrookes","type":"angel","check_min":1000000,"check_max":20000000,"stages":["seed","series-a","series-b"],"industries":["developer-tools","saas","climate","ai"],"portfolio":["Atlassian","Boundless Earth"],"verified":True},
{"name":"Scott Farquhar","bio":"Co-founder and CEO of Atlassian. Angel investor in developer productivity and SaaS.","location":"Sydney","country":"Australia","type":"angel","check_min":1000000,"check_max":20000000,"stages":["seed","series-a"],"industries":["developer-tools","saas","enterprise"],"portfolio":["Atlassian"],"verified":True},

# ═══════════════════════════════════════════════════════════
# FEMALE INVESTORS
# ═══════════════════════════════════════════════════════════
{"name":"Sukhinder Singh Cassidy","bio":"Founder of Boardlist. Former CEO of StubHub. Angel investor and operator in consumer tech.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/sukhindersc","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas","fintech"],"portfolio":[],"verified":True},
{"name":"Kathryn Minshew","bio":"Co-founder and CEO of The Muse. Angel investor in future-of-work and HR tech.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/kminshew","type":"angel","check_min":25000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["hr-tech","future-of-work","saas","consumer"],"portfolio":["The Muse"],"verified":True},
{"name":"Leah Busque","bio":"Founder of TaskRabbit. Partner at Fuel Capital. Expert in marketplace and gig economy.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/leahbusque","type":"vc","check_min":500000,"check_max":3000000,"stages":["seed","series-a"],"industries":["marketplace","consumer","saas","future-of-work"],"portfolio":["TaskRabbit"],"verified":True},
{"name":"Erin Griffith","bio":"Tech journalist and angel investor. Reporter at NY Times. Invests small amounts in early-stage.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/eringriffith","type":"angel","check_min":5000,"check_max":50000,"stages":["pre-seed"],"industries":["media","consumer","saas"],"portfolio":[],"verified":False},
{"name":"Joelle Emerson","bio":"Founder and CEO of Paradigm. Angel investor in DEI-focused and inclusive tech.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/joelleemerson","type":"angel","check_min":10000,"check_max":100000,"stages":["pre-seed","seed"],"industries":["hr-tech","saas","consumer","impact"],"portfolio":[],"verified":True},
{"name":"Nisha Dua","bio":"General Partner at BBG Ventures. Invests in female-founded consumer and tech companies.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/nishadua","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","saas","marketplace","health"],"portfolio":[],"verified":True},
{"name":"Anu Duggal","bio":"Founding Partner at Female Founders Fund. Expert in female-founded tech companies.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/anuduggal","type":"vc","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","health","fintech","marketplace"],"portfolio":["Zola","Thinx","Maven Clinic"],"verified":True},
{"name":"Serena Williams","bio":"Tennis legend and Founding Partner at Serena Ventures. Invests in diverse founders.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/serenawilliams","type":"vc","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["consumer","health","fintech","media","saas"],"portfolio":["MasterClass","Poshmark","Buzzfeed"],"verified":True},

# ═══════════════════════════════════════════════════════════
# ANGELS FROM SPECIFIC SECTORS
# ═══════════════════════════════════════════════════════════
{"name":"Kim-Mai Cutler","bio":"Partner at Initialized Capital. Former journalist at TechCrunch. Expert in housing and urban tech.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/kimmaicutler","type":"vc","check_min":500000,"check_max":3000000,"stages":["seed","series-a"],"industries":["real-estate","marketplace","consumer","saas"],"portfolio":[],"verified":True},
{"name":"Alexia Bonatsos","bio":"Founder of Dream Machine VC. Former TechCrunch editor. Invests in next-generation internet.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/alexia","type":"vc","check_min":250000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","ai","creator-economy","gaming"],"portfolio":[],"verified":True},
{"name":"Paige Craig","bio":"Managing Partner at Arena VC. Early investor in Twitter, Lyft, Wish, Postmates. Super active angel.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/paigecraig","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas","fintech","ai"],"portfolio":["Twitter","Lyft","Wish","Postmates"],"verified":True},
{"name":"Mike Maples Jr","bio":"Co-founder of Floodgate. Early investor in Twitter, Twitch, Lyft, Okta.","location":"Palo Alto, CA","country":"USA","twitter_url":"https://twitter.com/m2jr","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","ai"],"portfolio":["Twitter","Twitch","Lyft","Okta","Weebly"],"verified":True},
{"name":"Ann Miura-Ko","bio":"Co-founder of Floodgate. Professor at Stanford. Early investor in Lyft, TaskRabbit, Refinery29.","location":"Palo Alto, CA","country":"USA","twitter_url":"https://twitter.com/annimaniac","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","future-of-work"],"portfolio":["Lyft","TaskRabbit","Refinery29","Xamarin"],"verified":True},
{"name":"Charles Hudson","bio":"Managing Partner at Precursor Ventures. Invests in very early-stage diverse founders.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/chudson","type":"vc","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","gaming"],"portfolio":[],"verified":True},
{"name":"Manu Kumar","bio":"Founder of K9 Ventures. Professor at Stanford. Early stage angel in SaaS and developer tools.","location":"Palo Alto, CA","country":"USA","twitter_url":"https://twitter.com/manu","type":"angel","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["developer-tools","saas","enterprise","ai"],"portfolio":["Lyft","Twilio","Carta"],"verified":True},
{"name":"Hadley Harris","bio":"Co-founder of Eniac Ventures. Early mobile investor. Expert in mobile-first B2C companies.","location":"New York, NY","country":"USA","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["consumer","mobile","saas","marketplace"],"portfolio":[],"verified":True},
{"name":"Nihal Mehta","bio":"Founding General Partner at Eniac Ventures. Mobile ad pioneer. Angel in mobile-first startups.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/nihalmehta","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["consumer","mobile","saas","marketplace","ai"],"portfolio":[],"verified":True},
{"name":"Phil Libin","bio":"Co-founder of Evernote and All Turtles. Angel investor in AI and consumer productivity.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/plibin","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["ai","consumer","saas","developer-tools"],"portfolio":["Evernote"],"verified":True},
{"name":"Josh Elman","bio":"Partner at Greylock, former product at Twitter, Facebook, LinkedIn. Consumer and growth expert.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/joshelman","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","saas","social","marketplace"],"portfolio":["Robinhood","Medium","Discord"],"verified":True},
{"name":"Turner Novak","bio":"Founder of Banana Capital. Expert in consumer, gaming, and creator economy. Active tweeter/analyst.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/TurnerNovak","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","gaming","creator-economy","marketplace"],"portfolio":[],"verified":True},
{"name":"Harry Stebbings","bio":"Founder of 20VC and 20Growth. Active angel investor. One of the most networked people in VC.","location":"London","country":"UK","twitter_url":"https://twitter.com/HarryStebbings","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","consumer","fintech","ai","marketplace"],"portfolio":[],"verified":True},

# ═══════════════════════════════════════════════════════════
# ACCELERATORS AND PROGRAMS
# ═══════════════════════════════════════════════════════════
{"name":"Antler","bio":"Global early-stage VC. Invests $200K for 10% in 25+ countries. One of the most active accelerators worldwide.","location":"Singapore / Global","country":"Singapore","website":"https://antler.co","type":"accelerator","check_min":200000,"check_max":200000,"stages":["pre-seed"],"industries":["saas","ai","fintech","marketplace","consumer","developer-tools"],"portfolio":[],"verified":True},
{"name":"Entrepreneur First","bio":"Talent investor. Backs individuals before they have a co-founder or idea. Operates in 7 cities.","location":"London / Global","country":"UK","website":"https://joinef.com","type":"accelerator","check_min":80000,"check_max":500000,"stages":["pre-seed"],"industries":["ai","deep-tech","saas","fintech","biotech"],"portfolio":["Magic Pony","Aztec Protocol","Wayve"],"verified":True},
{"name":"Pioneer","bio":"Remote accelerator for exceptional founders worldwide. $4K+ in prizes and services.","location":"San Francisco, CA","country":"USA","website":"https://pioneer.app","type":"accelerator","check_min":4000,"check_max":50000,"stages":["pre-seed"],"industries":["saas","ai","consumer","developer-tools","marketplace"],"portfolio":[],"verified":True},
{"name":"Plug and Play Tech Center","bio":"Global innovation platform. Accelerates 200+ startups per year across 40+ locations worldwide.","location":"Sunnyvale, CA","country":"USA","website":"https://plugandplaytechcenter.com","type":"accelerator","check_min":50000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["saas","fintech","ai","health","iot","supply-chain"],"portfolio":[],"verified":True},
{"name":"MassChallenge","bio":"Non-equity accelerator. Gives $2M+ in cash prizes yearly. Open to all industries globally.","location":"Boston, MA","country":"USA","website":"https://masschallenge.org","type":"accelerator","check_min":0,"check_max":250000,"stages":["pre-seed","seed"],"industries":["saas","health","ai","climate","consumer","fintech"],"portfolio":[],"verified":True},
{"name":"Alchemist Accelerator","bio":"B2B and enterprise-focused accelerator in Silicon Valley. 6-month program with $25K funding.","location":"San Francisco, CA","country":"USA","website":"https://alchemistaccelerator.com","type":"accelerator","check_min":25000,"check_max":100000,"stages":["pre-seed"],"industries":["saas","enterprise","ai","developer-tools","b2b"],"portfolio":[],"verified":True},
{"name":"Seedcamp","bio":"European pre-seed and seed investor. The top accelerator in Europe. Backed Revolut, UiPath, Wise.","location":"London","country":"UK","website":"https://seedcamp.com","type":"accelerator","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","fintech","ai","marketplace","developer-tools"],"portfolio":["Revolut","UiPath","Wise","Viz.ai"],"verified":True},

# ═══════════════════════════════════════════════════════════
# CRYPTO / WEB3 FOCUSED
# ═══════════════════════════════════════════════════════════
{"name":"Fred Ehrsam","bio":"Co-founder of Coinbase and Paradigm. Leading crypto-native VC with $2.5B fund.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/fehrsam","type":"vc","check_min":1000000,"check_max":100000000,"stages":["seed","series-a","series-b"],"industries":["crypto","web3","fintech","developer-tools"],"portfolio":["Coinbase","FTX","Uniswap","dYdX"],"verified":True},
{"name":"Matt Huang","bio":"Co-founder of Paradigm. Former partner at Sequoia. Leading crypto investor.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/matthuang","type":"vc","check_min":1000000,"check_max":100000000,"stages":["seed","series-a","series-b"],"industries":["crypto","web3","defi","developer-tools"],"portfolio":["Coinbase","Uniswap","Compound","Optimism"],"verified":True},
{"name":"Olaf Carlson-Wee","bio":"Founder of Polychain Capital. First employee at Coinbase. Pioneer crypto hedge fund manager.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/olafcw","type":"vc","check_min":1000000,"check_max":50000000,"stages":["seed","series-a"],"industries":["crypto","web3","defi"],"portfolio":["Coinbase","Dfinity","Compound"],"verified":True},
{"name":"Naval Ravikant","bio":"Co-founder of AngelList. Pioneer angel investor in crypto, SaaS, and marketplace companies.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/naval","website":"https://nav.al","type":"angel","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["saas","ai","crypto","marketplace","fintech"],"portfolio":["Twitter","Uber","Yammer","Stack Overflow","AngelList"],"verified":True},
{"name":"Linda Xie","bio":"Co-founder of Scalar Capital. Former product manager at Coinbase. Crypto and DeFi expert.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/ljxie","type":"vc","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["crypto","web3","defi","nft"],"portfolio":[],"verified":True},

]

# Deduplicate
seen = set()
UNIQUE = []
for inv in INVESTORS_500:
    key = inv["name"].lower().strip()
    if key not in seen:
        seen.add(key)
        UNIQUE.append(inv)

INVESTORS_500 = UNIQUE
print(f"[OK] Loaded {len(INVESTORS_500)} investors in extended seed data")
