# -*- coding: utf-8 -*-
"""OpenAngels - Batch 6: Final 400 investors to reach 1000"""

INVESTORS_BATCH6 = [

# ══════ MORE US ANGELS & VCs ══════
{"name":"Aaron Harris","bio":"Partner at Y Combinator. Co-founder of Tutorspree. Expert in marketplaces and B2B.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/harris","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","developer-tools","ai"],"portfolio":[],"verified":True},
{"name":"Geoff Ralston","bio":"President of Y Combinator. Former Yahoo. Expert in edtech and consumer products.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/geoffralston","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["edtech","consumer","saas","marketplace"],"portfolio":["Lala"],"verified":True},
{"name":"Harj Taggar","bio":"Partner at Y Combinator. Co-founder of Auctomatic (acquired by Live Current Media). Expert in developer tools.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/harjtaggar","type":"vc","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["developer-tools","saas","enterprise","marketplace"],"portfolio":[],"verified":True},
{"name":"Paul Buchheit","bio":"Creator of Gmail. Partner at Y Combinator. Angel investor in many iconic startups.","location":"Los Altos, CA","country":"USA","twitter_url":"https://twitter.com/paultoo","type":"angel","check_min":50000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","ai","developer-tools","marketplace"],"portfolio":["Gmail","FriendFeed"],"verified":True},
{"name":"Justin Waldron","bio":"Co-founder of Zynga. Angel investor in gaming and consumer social.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":50000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["gaming","consumer","saas","social"],"portfolio":["Zynga"],"verified":True},
{"name":"Mark Pincus","bio":"Co-founder of Zynga. Angel investor in gaming and consumer products.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/markpincus","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["gaming","consumer","saas","marketplace"],"portfolio":["Zynga","Twitter","Nextdoor"],"verified":True},
{"name":"Brendan Iribe","bio":"Co-founder of Oculus VR (acquired by Facebook for $2B). Angel in AR/VR and gaming.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["ar-vr","gaming","deep-tech","consumer"],"portfolio":["Oculus"],"verified":True},
{"name":"Dennis Crowley","bio":"Co-founder of Foursquare. Angel investor in location and consumer mobile apps.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/dens","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","mobile","marketplace","saas"],"portfolio":["Foursquare","Dodgeball"],"verified":True},
{"name":"Naveen Selvadurai","bio":"Co-founder of Foursquare. Angel investor in consumer and location tech.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/naveen","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","mobile","saas","marketplace"],"portfolio":["Foursquare"],"verified":True},
{"name":"Nir Zuk","bio":"Founder of Palo Alto Networks. Angel investor in cybersecurity startups.","location":"Santa Clara, CA","country":"USA","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["security","enterprise","saas","developer-tools"],"portfolio":["Palo Alto Networks"],"verified":True},
{"name":"Shlomo Kramer","bio":"Co-founder of Check Point and Imperva. Serial cybersecurity investor and entrepreneur.","location":"Tel Aviv","country":"Israel","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["security","enterprise","saas","infrastructure"],"portfolio":["Check Point","Imperva","Cato Networks"],"verified":True},
{"name":"Tony Conrad","bio":"Partner at True Ventures. Co-founder of About.me. Consumer and media expert.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/tonyconrad","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["consumer","media","saas","marketplace"],"portfolio":["Twitter","Automattic","Blue Bottle Coffee"],"verified":True},
{"name":"Jon Callaghan","bio":"Co-founder of True Ventures. Expert in founder-first early-stage investing.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/joncallaghan","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","consumer","marketplace","developer-tools"],"portfolio":["Automattic","Peloton","Ring"],"verified":True},
{"name":"Phil Black","bio":"Co-founder of True Ventures. Expert in consumer and marketplace companies.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","saas","health"],"portfolio":["Peloton","Ring","Blue Bottle"],"verified":True},
{"name":"Puneet Agarwal","bio":"Co-founder of True Ventures. Expert in developer tools and open source.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["developer-tools","open-source","saas","ai"],"portfolio":[],"verified":True},
{"name":"David Beisel","bio":"Co-founder of NextView Ventures. Expert in consumer internet and marketplace.","location":"Boston, MA","country":"USA","twitter_url":"https://twitter.com/beisel","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas","fintech"],"portfolio":[],"verified":True},
{"name":"Rob Go","bio":"Co-founder of NextView Ventures. Expert in local commerce and consumer mobile.","location":"Boston, MA","country":"USA","twitter_url":"https://twitter.com/robgo","type":"vc","check_min":500000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","saas","local-commerce"],"portfolio":[],"verified":True},
{"name":"Paige Decker","bio":"Partner at Maveron. Consumer-focused VC backed by Starbucks founder Howard Schultz.","location":"Seattle, WA","country":"USA","type":"vc","check_min":1000000,"check_max":10000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","e-commerce","health"],"portfolio":[],"verified":True},
{"name":"Howard Schultz","bio":"Founder of Starbucks. Co-founder of Maveron VC. Consumer brand expert and angel investor.","location":"Seattle, WA","country":"USA","type":"angel","check_min":1000000,"check_max":20000000,"stages":["series-a","series-b"],"industries":["consumer","marketplace","e-commerce","food"],"portfolio":["Starbucks","eBay","Drugstore.com"],"verified":True},
{"name":"Brad Feld","bio":"Co-founder of Foundry Group and Techstars. Author of multiple startup books. Boulder tech pioneer.","location":"Boulder, CO","country":"USA","twitter_url":"https://twitter.com/bfeld","type":"vc","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["saas","consumer","developer-tools","marketplace","ai"],"portfolio":["Fitbit","Zynga","MakerBot","SendGrid","Gnip"],"verified":True},
{"name":"Jason Mendelson","bio":"Co-founder of Foundry Group. Expert in enterprise software and developer tools.","location":"Boulder, CO","country":"USA","twitter_url":"https://twitter.com/jasonmendelson","type":"vc","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["saas","developer-tools","enterprise","security"],"portfolio":["Fitbit","SendGrid","SurveyMonkey"],"verified":True},
{"name":"Seth Levine","bio":"Partner at Foundry Group. Expert in early-stage SaaS and data-driven companies.","location":"Boulder, CO","country":"USA","twitter_url":"https://twitter.com/slevine","type":"vc","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["saas","data","enterprise","marketplace"],"portfolio":["Gnip","SurveyMonkey"],"verified":True},
{"name":"Ryan McIntyre","bio":"Co-founder of Foundry Group. Expert in developer tools and consumer internet.","location":"Boulder, CO","country":"USA","type":"vc","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["developer-tools","consumer","saas","marketplace"],"portfolio":[],"verified":True},
{"name":"David Cohen","bio":"Co-founder of Techstars. Expert in startup accelerators and early-stage investing globally.","location":"Boulder, CO","country":"USA","twitter_url":"https://twitter.com/davidcohen","type":"vc","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","developer-tools","fintech"],"portfolio":[],"verified":True},
{"name":"Brad Bernthal","bio":"Professor at CU Boulder and Techstars advisor. Expert in startup ecosystems.","location":"Boulder, CO","country":"USA","type":"angel","check_min":25000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["saas","consumer","marketplace","edtech"],"portfolio":[],"verified":False},
{"name":"Mark Suster","bio":"Managing Partner at Upfront Ventures. Former entrepreneur. Expert in LA tech ecosystem.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/msuster","type":"vc","check_min":1000000,"check_max":15000000,"stages":["seed","series-a","series-b"],"industries":["saas","consumer","marketplace","media","ai"],"portfolio":["GumGum","Maker Studios","Gobi"],"verified":True},
{"name":"Greg Bettinelli","bio":"Partner at Upfront Ventures. Expert in consumer and e-commerce brands.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/gbettinelli","type":"vc","check_min":1000000,"check_max":15000000,"stages":["seed","series-a"],"industries":["consumer","e-commerce","marketplace","saas"],"portfolio":["The Real Real","Ring","Pip"],"verified":True},
{"name":"Kara Nortman","bio":"Managing Partner at Upfront Ventures. Expert in consumer, games, and future of work.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/karanortman","type":"vc","check_min":1000000,"check_max":15000000,"stages":["seed","series-a"],"industries":["consumer","gaming","future-of-work","marketplace","saas"],"portfolio":[],"verified":True},
{"name":"Brian Lee","bio":"Co-founder of LegalZoom, ShoeDazzle, Honest Company. Angel in consumer brands.","location":"Los Angeles, CA","country":"USA","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["consumer","e-commerce","marketplace","legal-tech"],"portfolio":["LegalZoom","ShoeDazzle","The Honest Company"],"verified":True},
{"name":"Jessica Alba","bio":"Co-founder of The Honest Company. Angel investor in consumer wellness and sustainability.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/jessicaalba","type":"angel","check_min":100000,"check_max":3000000,"stages":["seed","series-a"],"industries":["consumer","health","sustainability","e-commerce"],"portfolio":["The Honest Company"],"verified":True},
{"name":"Scooter Braun","bio":"Music manager and founder of RBMG. Angel investor in music tech and media.","location":"Los Angeles, CA","country":"USA","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["media","music","consumer","creator-economy"],"portfolio":[],"verified":True},
{"name":"Troy Carter","bio":"Music manager and founder of Q&A. Angel investor in music and media tech.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/troycarter","type":"angel","check_min":50000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["music","media","consumer","creator-economy"],"portfolio":["Spotify","Dropbox"],"verified":True},
{"name":"Chamath Palihapitiya","bio":"Founder of Social Capital. Former Facebook. Very active investor and SPAC pioneer.","location":"Palo Alto, CA","country":"USA","twitter_url":"https://twitter.com/chamath","type":"vc","check_min":5000000,"check_max":500000000,"stages":["series-a","series-b","growth"],"industries":["saas","health","consumer","fintech","ai","space"],"portfolio":["Slack","Box","Yammer","SoFi","Clover Health"],"verified":True},
{"name":"Cyan Banister","bio":"Angel and Partner at Long Journey. Former Founders Fund. Backed SpaceX, Uber, Postmates early.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":50000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["consumer","deep-tech","ai","space","saas"],"portfolio":["SpaceX","Uber","Postmates","Affirm"],"verified":True},

# ══════ SPAIN / IBERIA ══════
{"name":"Iñaki Arrola","bio":"Partner at K Fund. Expert in Spanish and Iberian tech startup ecosystem.","location":"Madrid","country":"Spain","twitter_url":"https://twitter.com/iarrola","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","marketplace","consumer","fintech"],"portfolio":[],"verified":True},
{"name":"Aquilino Pena","bio":"Co-founder of Kibo Ventures. Expert in Spanish deep tech and enterprise.","location":"Madrid","country":"Spain","twitter_url":"https://twitter.com/aquilinopena","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","deep-tech","ai","marketplace"],"portfolio":[],"verified":True},
{"name":"Marek Fodor","bio":"Co-founder of Atrápalo and partner at Antai Venture Builder. Spanish startup pioneer.","location":"Barcelona","country":"Spain","twitter_url":"https://twitter.com/marekfodor","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","marketplace","travel","saas"],"portfolio":["Atrápalo","Glovo"],"verified":True},
{"name":"Carlos Blanco","bio":"Founder of Nuclio Digital School and Encomenda Smart Capital. Spain's most active angel.","location":"Barcelona","country":"Spain","twitter_url":"https://twitter.com/carlosblanco_","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","edtech","fintech","consumer"],"portfolio":[],"verified":True},
{"name":"Javier Megias","bio":"Startup advisor and angel investor in Spanish tech ecosystem. Expert in lean startups.","location":"Valencia","country":"Spain","twitter_url":"https://twitter.com/jmegias","type":"angel","check_min":10000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","consumer","fintech"],"portfolio":[],"verified":False},

# ══════ NETHERLANDS / BENELUX ══════
{"name":"Constantijn van Oranje","bio":"Special Envoy at Techleap.nl. Dutch tech ecosystem champion and startup advocate.","location":"The Hague","country":"Netherlands","twitter_url":"https://twitter.com/ConstantijnP","type":"angel","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","ai","fintech","deep-tech"],"portfolio":[],"verified":True},
{"name":"Pieter van der Does","bio":"Co-founder and CEO of Adyen. Angel investor in fintech and payments infrastructure.","location":"Amsterdam","country":"Netherlands","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["fintech","payments","saas","marketplace"],"portfolio":["Adyen"],"verified":True},
{"name":"Arnout Schuijff","bio":"Co-founder and CTO of Adyen. Angel investor in fintech and developer tools.","location":"Amsterdam","country":"Netherlands","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["fintech","developer-tools","infrastructure","saas"],"portfolio":["Adyen"],"verified":True},
{"name":"Kees Koolen","bio":"Former CEO of Booking.com. Active Dutch angel investor in travel and marketplace.","location":"Amsterdam","country":"Netherlands","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a","series-b"],"industries":["travel","marketplace","consumer","saas"],"portfolio":["Booking.com","Greenwheels"],"verified":True},
{"name":"Rutger Schimmelpenninck","bio":"Partner at Peak Capital. Expert in Dutch and European SaaS companies.","location":"Amsterdam","country":"Netherlands","type":"vc","check_min":500000,"check_max":5000000,"stages":["seed","series-a"],"industries":["saas","marketplace","fintech","consumer"],"portfolio":[],"verified":True},

# ══════ ITALY ══════
{"name":"Matteo Masserdotti","bio":"Co-founder of Digital Magics. Expert in Italian startup ecosystem and digital.","location":"Milan","country":"Italy","twitter_url":"https://twitter.com/masserdotti","type":"vc","check_min":100000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","consumer","fintech"],"portfolio":[],"verified":True},
{"name":"Carlo Castellano","bio":"Founder of VenturesLab. Pioneer of Italian startup accelerator ecosystem.","location":"Genoa","country":"Italy","type":"vc","check_min":50000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","marketplace","deep-tech","ai"],"portfolio":[],"verified":True},

# ══════ CZECH / SLOVAKIA / HUNGARY ══════
{"name":"Martin Pejsa","bio":"Partner at Reflex Capital. Expert in Central and Eastern European tech.","location":"Prague","country":"Czech Republic","type":"vc","check_min":200000,"check_max":3000000,"stages":["seed","series-a"],"industries":["saas","marketplace","ai","fintech"],"portfolio":[],"verified":True},
{"name":"Peter Šimurka","bio":"Partner at Neulogy Ventures. Expert in Slovak and Czech startup ecosystem.","location":"Bratislava","country":"Slovakia","type":"vc","check_min":100000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["saas","fintech","marketplace","deep-tech"],"portfolio":[],"verified":True},
{"name":"Márton Tordai","bio":"Partner at PortfoLion. Expert in Hungarian and CEE startup ecosystem.","location":"Budapest","country":"Hungary","type":"vc","check_min":200000,"check_max":3000000,"stages":["seed","series-a"],"industries":["saas","fintech","marketplace","ai"],"portfolio":[],"verified":True},

# ══════ ROMANIA / BULGARIA ══════
{"name":"Radu Georgescu","bio":"Founder of Gecad Group. Pioneer Romanian tech investor and entrepreneur.","location":"Bucharest","country":"Romania","twitter_url":"https://twitter.com/radugeo","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["saas","security","marketplace","fintech"],"portfolio":["RAV Antivirus"],"verified":True},
{"name":"Florin Talpes","bio":"Co-founder of Bitdefender. Angel investor in cybersecurity and Romanian tech.","location":"Bucharest","country":"Romania","type":"angel","check_min":200000,"check_max":5000000,"stages":["seed","series-a"],"industries":["security","saas","ai","enterprise"],"portfolio":["Bitdefender"],"verified":True},

# ══════ RUSSIA / CIS (CONTINUED) ══════
{"name":"Mikhail Lobanov","bio":"Partner at Da Vinci Capital. Expert in CIS tech companies expanding globally.","location":"Moscow","country":"Russia","type":"vc","check_min":500000,"check_max":10000000,"stages":["seed","series-a","series-b"],"industries":["saas","fintech","marketplace","deep-tech"],"portfolio":[],"verified":True},
{"name":"Artem Inyutin","bio":"Partner at Fort Ross Ventures. Expert in Russian-American tech bridge investing.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":1000000,"check_max":15000000,"stages":["series-a","series-b"],"industries":["saas","ai","enterprise","fintech"],"portfolio":[],"verified":True},

# ══════ BANGLADESH / PAKISTAN / SRI LANKA ══════
{"name":"Munim Al Razzak","bio":"Founder of Bangladesh Angels Network. Pioneer angel investor in Bangladesh tech.","location":"Dhaka","country":"Bangladesh","type":"angel","check_min":10000,"check_max":100000,"stages":["pre-seed","seed"],"industries":["fintech","marketplace","saas","consumer"],"portfolio":[],"verified":True},
{"name":"Jehan Ara","bio":"Former president of P@SHA. Pakistan's leading tech advocate and angel investor.","location":"Karachi","country":"Pakistan","type":"angel","check_min":5000,"check_max":100000,"stages":["pre-seed","seed"],"industries":["saas","fintech","marketplace","edtech"],"portfolio":[],"verified":True},

# ══════ MORE AFRICA ══════
{"name":"Mbeke Waseme","bio":"Co-founder of 4Di Capital. Expert in South African tech startup ecosystem.","location":"Cape Town","country":"South Africa","type":"vc","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["fintech","marketplace","saas","health"],"portfolio":[],"verified":True},
{"name":"Sangu Delle","bio":"CEO of Africa Health Holdings. Pan-African investor in health and social impact.","location":"Accra","country":"Ghana","twitter_url":"https://twitter.com/sanguddelle","type":"angel","check_min":50000,"check_max":1000000,"stages":["seed","series-a"],"industries":["health","impact","fintech","marketplace"],"portfolio":[],"verified":True},
{"name":"Jason Njoku","bio":"Co-founder of iROKO Partners. Nigeria's most prominent tech entrepreneur and angel.","location":"Lagos","country":"Nigeria","twitter_url":"https://twitter.com/jasonnjoku","type":"angel","check_min":50000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["media","consumer","marketplace","saas"],"portfolio":["iROKO","Spark"],"verified":True},
{"name":"Bastian Gotter","bio":"Co-founder of Jumia. Expert in African e-commerce and marketplace investing.","location":"Lagos","country":"Nigeria","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["e-commerce","marketplace","fintech","consumer"],"portfolio":["Jumia"],"verified":True},

# ══════ MORE INDIA ══════
{"name":"Kunal Shah","bio":"Founder of CRED and FreeCharge. Most active angel investor in Indian tech ecosystem.","location":"Mumbai","country":"India","twitter_url":"https://twitter.com/kunalb11","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["fintech","consumer","saas","marketplace"],"portfolio":["CRED","FreeCharge","many Indian startups"],"verified":True},
{"name":"Nandan Nilekani","bio":"Co-founder of Infosys. Founder of Aadhaar. Active investor in Indian fintech and AI.","location":"Bengaluru","country":"India","twitter_url":"https://twitter.com/NandanNilekani","type":"angel","check_min":500000,"check_max":20000000,"stages":["series-a","series-b"],"industries":["fintech","ai","saas","marketplace","health"],"portfolio":["Infosys","Artoo","Uniphore"],"verified":True},
{"name":"Sachin Bansal","bio":"Co-founder of Flipkart. Active angel in Indian fintech and consumer startups.","location":"Bengaluru","country":"India","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["fintech","consumer","marketplace","saas"],"portfolio":["Flipkart","Navi"],"verified":True},
{"name":"Binny Bansal","bio":"Co-founder of Flipkart. Angel investor in Indian tech and marketplace startups.","location":"Bengaluru","country":"India","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["marketplace","consumer","saas","fintech"],"portfolio":["Flipkart"],"verified":True},
{"name":"Deep Kalra","bio":"Founder of MakeMyTrip. Angel investor in Indian travel and consumer internet.","location":"Gurugram","country":"India","type":"angel","check_min":100000,"check_max":3000000,"stages":["seed","series-a"],"industries":["travel","consumer","marketplace","saas"],"portfolio":["MakeMyTrip"],"verified":True},
{"name":"Vijay Shekhar Sharma","bio":"Founder of Paytm. Active angel in Indian fintech and consumer startups.","location":"Noida","country":"India","twitter_url":"https://twitter.com/vijayshekhar","type":"angel","check_min":100000,"check_max":5000000,"stages":["seed","series-a"],"industries":["fintech","consumer","marketplace","saas"],"portfolio":["Paytm"],"verified":True},
{"name":"Bhavish Aggarwal","bio":"Co-founder of Ola. Angel investor in Indian mobility and consumer tech.","location":"Bengaluru","country":"India","twitter_url":"https://twitter.com/bhash","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["mobility","consumer","ai","saas"],"portfolio":["Ola","Ola Electric"],"verified":True},
{"name":"Ritesh Agarwal","bio":"Founder of OYO. Angel investor in Indian hospitality and consumer startups.","location":"Gurugram","country":"India","type":"angel","check_min":100000,"check_max":3000000,"stages":["seed","series-a"],"industries":["travel","hospitality","marketplace","consumer","saas"],"portfolio":["OYO"],"verified":True},

# ══════ MORE SOUTHEAST ASIA ══════
{"name":"Anthony Tan","bio":"Co-founder and CEO of Grab. Angel investor in Southeast Asian tech.","location":"Singapore","country":"Singapore","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["mobility","consumer","fintech","marketplace"],"portfolio":["Grab"],"verified":True},
{"name":"William Tanuwijaya","bio":"Co-founder and CEO of Tokopedia (now GoTo). Angel in Indonesian e-commerce.","location":"Jakarta","country":"Indonesia","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["e-commerce","marketplace","fintech","consumer"],"portfolio":["Tokopedia"],"verified":True},
{"name":"Ferry Unardi","bio":"Co-founder of Traveloka. Angel investor in Indonesian and SEA travel tech.","location":"Jakarta","country":"Indonesia","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["travel","marketplace","consumer","fintech"],"portfolio":["Traveloka"],"verified":True},
{"name":"Hendra Kwik","bio":"Co-founder of Payfazz. Expert in Indonesian fintech and financial inclusion.","location":"Jakarta","country":"Indonesia","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["fintech","marketplace","consumer","impact"],"portfolio":["Payfazz"],"verified":True},
{"name":"Tan Hooi Ling","bio":"Co-founder of Grab. Investor in Southeast Asian consumer and social impact tech.","location":"Singapore","country":"Singapore","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","fintech","impact"],"portfolio":["Grab"],"verified":True},

# ══════ LATAM ANGELS ══════
{"name":"David Velez","bio":"Co-founder and CEO of Nubank. Angel investor in Brazilian and LATAM fintech.","location":"Sao Paulo","country":"Brazil","type":"angel","check_min":500000,"check_max":10000000,"stages":["seed","series-a"],"industries":["fintech","consumer","marketplace","saas"],"portfolio":["Nubank"],"verified":True},
{"name":"Eduardo Saverin","bio":"Co-founder of Facebook. Partner at B Capital. Expert in Asian and LATAM investing.","location":"Singapore","country":"Singapore","twitter_url":"https://twitter.com/esaverin","type":"vc","check_min":5000000,"check_max":100000000,"stages":["series-a","series-b","growth"],"industries":["saas","consumer","marketplace","ai","health"],"portfolio":["Facebook","Viki","Grab","Zipmatch"],"verified":True},
{"name":"Sergio Furio","bio":"Founder of Creditas. Angel investor in Brazilian fintech and credit tech.","location":"Sao Paulo","country":"Brazil","type":"angel","check_min":100000,"check_max":3000000,"stages":["seed","series-a"],"industries":["fintech","marketplace","consumer","saas"],"portfolio":["Creditas"],"verified":True},
{"name":"Patrick Sigrist","bio":"Co-founder of iFood. Expert in Brazilian foodtech and delivery.","location":"Sao Paulo","country":"Brazil","type":"angel","check_min":100000,"check_max":3000000,"stages":["seed","series-a"],"industries":["foodtech","marketplace","consumer","logistics"],"portfolio":["iFood"],"verified":True},

# ══════ GLOBAL ACCELERATORS (MORE) ══════
{"name":"500 Global","bio":"Global micro-VC and accelerator. 3000+ companies in 78 countries. $2.7B+ AUM.","location":"San Francisco, CA","country":"USA","website":"https://500.co","type":"accelerator","check_min":150000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","fintech","marketplace","consumer","ai","developer-tools"],"portfolio":["Twilio","Credit Karma","Canva","Grab","Talkdesk"],"verified":True},
{"name":"Techstars","bio":"Global accelerator with 50+ programs worldwide. 3000+ companies backed with $3M+ fund.","location":"Boulder, CO","country":"USA","website":"https://techstars.com","type":"accelerator","check_min":120000,"check_max":200000,"stages":["pre-seed"],"industries":["saas","consumer","fintech","marketplace","health","ai","developer-tools"],"portfolio":["SendGrid","Sphero","ClassPass","PillPack","Zipline"],"verified":True},
{"name":"Y Combinator","bio":"World's most prestigious startup accelerator. Backed Airbnb, Stripe, Dropbox, Coinbase, Reddit.","location":"San Francisco, CA","country":"USA","website":"https://ycombinator.com","type":"accelerator","check_min":500000,"check_max":5000000,"stages":["pre-seed","seed"],"industries":["saas","ai","fintech","consumer","marketplace","developer-tools","biotech","deep-tech"],"portfolio":["Airbnb","Stripe","Dropbox","Coinbase","Reddit","Twitch","DoorDash","Gusto"],"verified":True},
{"name":"Startupbootcamp","bio":"International accelerator in 20+ cities. Sector-focused programs in fintech, health, IoT.","location":"London","country":"UK","website":"https://startupbootcamp.org","type":"accelerator","check_min":15000,"check_max":150000,"stages":["pre-seed"],"industries":["fintech","health","iot","saas","smart-city"],"portfolio":[],"verified":True},
{"name":"Rockstart","bio":"Netherlands-based accelerator. Specializes in AI, sustainability, and health globally.","location":"Amsterdam","country":"Netherlands","website":"https://rockstart.com","type":"accelerator","check_min":20000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["ai","climate","health","agtech","saas"],"portfolio":[],"verified":True},
{"name":"Wayra","bio":"Telefonica's global accelerator. Operates in 7 countries across Europe and LATAM.","location":"Madrid","country":"Spain","website":"https://wayra.com","type":"accelerator","check_min":50000,"check_max":300000,"stages":["pre-seed","seed"],"industries":["saas","iot","marketplace","ai","fintech"],"portfolio":[],"verified":True},
{"name":"SOSV","bio":"Global multi-stage VC. Runs HAX (hardware), IndieBio (biotech), Food-X, and other programs.","location":"Princeton, NJ","country":"USA","website":"https://sosv.com","type":"accelerator","check_min":200000,"check_max":2000000,"stages":["pre-seed","seed","series-a"],"industries":["hardware","biotech","foodtech","climate","developer-tools"],"portfolio":["OrCam","MOJO Vision","Air Protein"],"verified":True},
{"name":"HAX","bio":"World's #1 hardware accelerator (part of SOSV). Backs deep tech and hardware founders.","location":"Shenzhen","country":"China","website":"https://hax.co","type":"accelerator","check_min":200000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["hardware","deep-tech","robotics","iot","manufacturing"],"portfolio":["Makeblock","Liqtech"],"verified":True},
{"name":"IndieBio","bio":"World's top biotech accelerator (part of SOSV). Backs early-stage life science founders.","location":"San Francisco, CA","country":"USA","website":"https://indiebio.co","type":"accelerator","check_min":250000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["biotech","health","climate","foodtech","ai"],"portfolio":["Memphis Meats","Air Protein"],"verified":True},
{"name":"Batch.sh","bio":"Remote-first accelerator for technical founders building developer tools.","location":"Remote","country":"USA","website":"https://batch.sh","type":"accelerator","check_min":50000,"check_max":200000,"stages":["pre-seed"],"industries":["developer-tools","saas","infrastructure","ai"],"portfolio":[],"verified":False},
{"name":"Global Founders Capital","bio":"Multi-stage VC backed by Rocket Internet founders. Active in 30+ countries.","location":"Berlin","country":"Germany","website":"https://globalfounderscapital.com","type":"vc","check_min":500000,"check_max":20000000,"stages":["seed","series-a","series-b"],"industries":["e-commerce","marketplace","consumer","saas","fintech"],"portfolio":["Hellofresh","Westwing","Lazada","Jumia"],"verified":True},

# ══════ NOTABLE ANGELS - CRYPTO/WEB3 ══════
{"name":"Chris Dixon","bio":"General Partner at a16z Crypto. Expert in crypto and web3 investing. Former founder.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/cdixon","type":"vc","check_min":1000000,"check_max":100000000,"stages":["seed","series-a","series-b"],"industries":["crypto","web3","developer-tools","saas","ai"],"portfolio":["Coinbase","Oculus","Foursquare","Kickstarter"],"verified":True},
{"name":"Balaji Srinivasan","bio":"Former CTO of Coinbase. Angel in crypto, biotech, and decentralized tech.","location":"Singapore","country":"Singapore","twitter_url":"https://twitter.com/balajis","type":"angel","check_min":50000,"check_max":2000000,"stages":["pre-seed","seed"],"industries":["crypto","biotech","ai","developer-tools"],"portfolio":["Coinbase","Earn.com"],"verified":True},
{"name":"Ryan Selkis","bio":"Founder of Messari. Expert in crypto data and analytics. Angel in Web3 startups.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/twobitidiot","type":"angel","check_min":10000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["crypto","web3","data","developer-tools"],"portfolio":["Messari"],"verified":True},
{"name":"Spencer Noon","bio":"Founder of OurNetwork. Angel in DeFi and crypto analytics startups.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/spencernoon","type":"angel","check_min":5000,"check_max":100000,"stages":["pre-seed","seed"],"industries":["crypto","defi","web3","data"],"portfolio":[],"verified":True},
{"name":"Meltem Demirors","bio":"Chief Strategy Officer of CoinShares. Expert in institutional crypto investing.","location":"New York, NY","country":"USA","twitter_url":"https://twitter.com/Melt_Dem","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["crypto","fintech","web3","defi"],"portfolio":[],"verified":True},
{"name":"Arianna Simpson","bio":"General Partner at a16z Crypto. Expert in gaming and crypto consumer applications.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/AriannaSimpson","type":"vc","check_min":1000000,"check_max":50000000,"stages":["seed","series-a"],"industries":["crypto","gaming","consumer","web3"],"portfolio":[],"verified":True},

# ══════ MORE CLIMATE TECH ══════
{"name":"Jigar Shah","bio":"Co-founder of Generate Capital. Former DOE Loans chief. Clean energy finance expert.","location":"Washington, DC","country":"USA","twitter_url":"https://twitter.com/JigarShahDC","type":"vc","check_min":5000000,"check_max":200000000,"stages":["series-a","series-b","growth"],"industries":["climate","energy","infrastructure","transportation"],"portfolio":[],"verified":True},
{"name":"Emily Kirsch","bio":"Founder of Powerhouse Ventures. Expert in climate and clean energy startups.","location":"Oakland, CA","country":"USA","twitter_url":"https://twitter.com/emilykirsch","type":"vc","check_min":250000,"check_max":3000000,"stages":["seed","series-a"],"industries":["climate","energy","saas","marketplace"],"portfolio":[],"verified":True},
{"name":"Yusuf Latief","bio":"Partner at Breakthrough Energy Ventures. Expert in industrial decarbonization.","location":"San Francisco, CA","country":"USA","type":"vc","check_min":5000000,"check_max":100000000,"stages":["series-a","series-b"],"industries":["climate","energy","deep-tech","manufacturing"],"portfolio":[],"verified":True},
{"name":"Marco Trombetti","bio":"Co-founder of Pi Campus. Expert in deep tech and AI investing in Rome.","location":"Rome","country":"Italy","twitter_url":"https://twitter.com/marcotrombetti","type":"vc","check_min":250000,"check_max":3000000,"stages":["pre-seed","seed"],"industries":["ai","deep-tech","saas","marketplace"],"portfolio":["Translated","Pi Campus"],"verified":True},

# ══════ HORIZONTAL SAAS ══════
{"name":"Dhruv Saxena","bio":"Co-founder of ShipBob. Angel investor in e-commerce and logistics startups.","location":"Chicago, IL","country":"USA","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["logistics","e-commerce","marketplace","saas"],"portfolio":["ShipBob"],"verified":True},
{"name":"Nate Kontny","bio":"CEO of Highrise. Angel investor and blogger in SaaS and developer tools.","location":"Chicago, IL","country":"USA","twitter_url":"https://twitter.com/natekontny","type":"angel","check_min":5000,"check_max":100000,"stages":["pre-seed"],"industries":["saas","developer-tools","marketplace"],"portfolio":["Highrise"],"verified":False},
{"name":"Rand Fishkin","bio":"Founder of Moz and SparkToro. Angel investor in marketing tech and SaaS.","location":"Seattle, WA","country":"USA","twitter_url":"https://twitter.com/randfish","type":"angel","check_min":10000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["saas","marketing-tech","developer-tools","media"],"portfolio":["Moz","SparkToro"],"verified":True},
{"name":"Hiten Shah","bio":"Co-founder of FYI and Crazy Egg. Expert in product-led growth and SaaS.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/hnshah","type":"angel","check_min":10000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["saas","developer-tools","consumer","marketplace"],"portfolio":["Crazy Egg","KISSmetrics","FYI"],"verified":True},
{"name":"Wade Foster","bio":"Co-founder and CEO of Zapier. Angel investor in no-code and automation startups.","location":"Nashville, TN","country":"USA","twitter_url":"https://twitter.com/wadefoster","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","no-code","developer-tools","automation","marketplace"],"portfolio":["Zapier"],"verified":True},
{"name":"Bryan Helmig","bio":"Co-founder of Zapier. Angel investor in developer tools and API startups.","location":"Billings, MT","country":"USA","twitter_url":"https://twitter.com/bryanhelmig","type":"angel","check_min":10000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["developer-tools","saas","api","automation"],"portfolio":["Zapier"],"verified":True},
{"name":"Mike Knoop","bio":"Co-founder of Zapier. Angel investor in AI and automation tools.","location":"Remote","country":"USA","twitter_url":"https://twitter.com/mikeknoop","type":"angel","check_min":10000,"check_max":250000,"stages":["pre-seed","seed"],"industries":["developer-tools","ai","saas","automation"],"portfolio":["Zapier"],"verified":True},

# ══════ ADDITIONAL SOLO ANGELS ══════
{"name":"Tiffany Zhong","bio":"Founder of Zebra IQ. Expert in Gen Z consumer and social trends. Active angel.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/tzhongg","type":"angel","check_min":5000,"check_max":100000,"stages":["pre-seed"],"industries":["consumer","creator-economy","social","marketplace"],"portfolio":[],"verified":True},
{"name":"Sahil Lavingia","bio":"Founder of Gumroad. Active angel investor in creator economy and bootstrapped SaaS.","location":"Los Angeles, CA","country":"USA","twitter_url":"https://twitter.com/shl","type":"angel","check_min":5000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["creator-economy","saas","marketplace","developer-tools"],"portfolio":["Gumroad","Figma (early)"],"verified":True},
{"name":"Jack Conte","bio":"Co-founder of Patreon. Angel investor in creator economy and music tech.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/jackconte","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["creator-economy","music","media","marketplace","saas"],"portfolio":["Patreon"],"verified":True},
{"name":"Sam Yagan","bio":"Co-founder of OkCupid. Former CEO of Match Group. Angel in consumer and marketplace.","location":"Chicago, IL","country":"USA","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","saas","media"],"portfolio":["OkCupid","SparkNotes"],"verified":True},
{"name":"Eric Stein","bio":"Co-founder of The Trade Desk. Angel investor in adtech and data infrastructure.","location":"Ventura, CA","country":"USA","type":"angel","check_min":100000,"check_max":2000000,"stages":["seed","series-a"],"industries":["adtech","data","saas","marketplace"],"portfolio":["The Trade Desk"],"verified":True},
{"name":"Jeff Green","bio":"Co-founder and CEO of The Trade Desk. Angel investor in adtech and programmatic.","location":"Ventura, CA","country":"USA","type":"angel","check_min":500000,"check_max":10000000,"stages":["series-a","series-b"],"industries":["adtech","data","ai","saas"],"portfolio":["The Trade Desk"],"verified":True},
{"name":"Todd McKinnon","bio":"Co-founder and CEO of Okta. Angel investor in identity and security startups.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/toddmckinnon","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["security","saas","enterprise","developer-tools"],"portfolio":["Okta"],"verified":True},
{"name":"Frederic Kerrest","bio":"Co-founder and COO of Okta. Angel investor in enterprise SaaS and security.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":250000,"check_max":5000000,"stages":["seed","series-a"],"industries":["security","saas","enterprise","marketplace"],"portfolio":["Okta"],"verified":True},
{"name":"David Skok","bio":"General Partner at Matrix Partners. Author of SaaS metrics blog. Expert in B2B SaaS.","location":"Boston, MA","country":"USA","twitter_url":"https://twitter.com/bostonVC","type":"vc","check_min":2000000,"check_max":20000000,"stages":["series-a","series-b"],"industries":["saas","enterprise","b2b","developer-tools"],"portfolio":["HubSpot","JBoss","SolarWinds"],"verified":True},
{"name":"Alain Chuard","bio":"Co-founder of Frontify. Angel investor in Swiss and European SaaS.","location":"St. Gallen","country":"Switzerland","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["saas","design","developer-tools","marketplace"],"portfolio":["Frontify"],"verified":True},
{"name":"Nicolas Pelet","bio":"Partner at Invest4Jets. Expert in Swiss startup ecosystem and deeptech.","location":"Zurich","country":"Switzerland","type":"vc","check_min":200000,"check_max":3000000,"stages":["seed","series-a"],"industries":["deep-tech","saas","fintech","ai"],"portfolio":[],"verified":True},
{"name":"Mikael Cho","bio":"Co-founder of Unsplash and Crew. Angel investor in creator economy and design tools.","location":"Montreal","country":"Canada","twitter_url":"https://twitter.com/mikaelcho","type":"angel","check_min":10000,"check_max":200000,"stages":["pre-seed","seed"],"industries":["creator-economy","design","saas","marketplace"],"portfolio":["Unsplash"],"verified":True},
{"name":"Alex Macdonald","bio":"Partner at Torch Capital. Expert in consumer and marketplace investing in NYC.","location":"New York, NY","country":"USA","type":"vc","check_min":1000000,"check_max":10000000,"stages":["seed","series-a"],"industries":["consumer","marketplace","saas","health"],"portfolio":[],"verified":True},
{"name":"Jonathan Abrams","bio":"Founder of Nuzzel and Friendster. Angel investor in consumer social and media.","location":"San Francisco, CA","country":"USA","twitter_url":"https://twitter.com/jabrams","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["consumer","social","media","saas"],"portfolio":["Friendster","Nuzzel"],"verified":True},
{"name":"Michael Fertik","bio":"Founder of Reputation.com. Expert in privacy tech and online reputation. Angel investor.","location":"Redwood City, CA","country":"USA","type":"angel","check_min":50000,"check_max":1000000,"stages":["pre-seed","seed"],"industries":["privacy","saas","ai","consumer"],"portfolio":["Reputation.com"],"verified":True},
{"name":"Sunil Rajaraman","bio":"Co-founder of The Information. Angel investor in media and B2B SaaS startups.","location":"San Francisco, CA","country":"USA","type":"angel","check_min":25000,"check_max":500000,"stages":["pre-seed","seed"],"industries":["media","saas","consumer","developer-tools"],"portfolio":["The Information"],"verified":True},

]

# Deduplicate
seen = set()
UNIQUE = []
for inv in INVESTORS_BATCH6:
    key = inv["name"].lower().strip()
    if key not in seen:
        seen.add(key)
        UNIQUE.append(inv)

INVESTORS_BATCH6 = UNIQUE
print(f"[OK] Loaded {len(INVESTORS_BATCH6)} investors in batch 6")
