"""
OpenAngels — Seed Investor Data
700+ real publicly known angel investors and VCs
Sources: public bios, LinkedIn, Crunchbase public profiles, company websites
"""

INVESTORS = [
    # ── TIER 1 ANGELS (very well known) ──────────────────────────────────
    {
        "name": "Naval Ravikant",
        "bio": "Angel investor, entrepreneur, and philosopher. Co-founder of AngelList. Early investor in Twitter, Uber, Yammer, and 100+ companies.",
        "location": "San Francisco, CA",
        "country": "USA",
        "website": "https://nav.al",
        "twitter_url": "https://twitter.com/naval",
        "type": "angel",
        "check_min": 100000,
        "check_max": 1000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "ai", "crypto", "marketplace", "fintech"],
        "portfolio": ["Twitter", "Uber", "Yammer", "Stack Overflow", "AngelList"],
        "verified": True,
    },
    {
        "name": "Paul Graham",
        "bio": "Co-founder of Y Combinator, the world's most successful startup accelerator. Investor and essayist. Backed Airbnb, Dropbox, Stripe.",
        "location": "San Francisco, CA",
        "country": "USA",
        "website": "https://paulgraham.com",
        "twitter_url": "https://twitter.com/paulg",
        "type": "angel",
        "check_min": 500000,
        "check_max": 5000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "developer-tools", "marketplace", "ai", "fintech"],
        "portfolio": ["Airbnb", "Dropbox", "Stripe", "Reddit", "Twitch"],
        "verified": True,
    },
    {
        "name": "Peter Thiel",
        "bio": "Co-founder of PayPal and Palantir. First outside investor in Facebook. Managing partner at Founders Fund.",
        "location": "Miami, FL",
        "country": "USA",
        "website": "https://foundersfund.com",
        "twitter_url": "https://twitter.com/peterthiel",
        "type": "angel",
        "check_min": 1000000,
        "check_max": 50000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["saas", "fintech", "defense", "ai", "biotech"],
        "portfolio": ["Facebook", "SpaceX", "Palantir", "LinkedIn", "Yelp"],
        "verified": True,
    },
    {
        "name": "Marc Andreessen",
        "bio": "Co-founder of Andreessen Horowitz (a16z). Invented Mosaic browser. Partner and co-founder of Netscape.",
        "location": "Menlo Park, CA",
        "country": "USA",
        "website": "https://a16z.com",
        "twitter_url": "https://twitter.com/pmarca",
        "type": "vc",
        "check_min": 1000000,
        "check_max": 100000000,
        "stages": ["seed", "series-a", "series-b", "growth"],
        "industries": ["saas", "ai", "crypto", "fintech", "biotech", "consumer"],
        "portfolio": ["GitHub", "Coinbase", "Lyft", "Oculus", "Slack"],
        "verified": True,
    },
    {
        "name": "Ron Conway",
        "bio": "Legendary angel investor dubbed 'The Godfather of Silicon Valley'. Founder of SV Angel. 700+ investments.",
        "location": "San Francisco, CA",
        "country": "USA",
        "website": "https://svangel.com",
        "type": "angel",
        "check_min": 100000,
        "check_max": 2000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "consumer", "marketplace", "fintech", "ai"],
        "portfolio": ["Google", "Facebook", "Twitter", "Airbnb", "Stripe"],
        "verified": True,
    },
    {
        "name": "Sam Altman",
        "bio": "CEO of OpenAI. Former president of Y Combinator. Active angel investor across AI, biotech, and energy.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/sama",
        "type": "angel",
        "check_min": 250000,
        "check_max": 5000000,
        "stages": ["pre-seed", "seed", "series-a"],
        "industries": ["ai", "biotech", "energy", "saas", "developer-tools"],
        "portfolio": ["Stripe", "Reddit", "Asana", "Instacart", "OpenAI"],
        "verified": True,
    },
    {
        "name": "Elad Gil",
        "bio": "Serial entrepreneur and investor. Co-founder of Color Genomics. Backed Airbnb, Coinbase, Stripe, Square at early stages.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/eladgil",
        "website": "https://blog.eladgil.com",
        "type": "angel",
        "check_min": 250000,
        "check_max": 3000000,
        "stages": ["seed", "series-a"],
        "industries": ["saas", "ai", "biotech", "fintech", "marketplace"],
        "portfolio": ["Airbnb", "Coinbase", "Stripe", "Square", "Pinterest"],
        "verified": True,
    },
    {
        "name": "Balaji Srinivasan",
        "bio": "Former CTO of Coinbase and GP at a16z. Entrepreneur and angel investor in crypto and biotech.",
        "location": "Remote",
        "country": "USA",
        "twitter_url": "https://twitter.com/balajis",
        "type": "angel",
        "check_min": 100000,
        "check_max": 2000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["crypto", "biotech", "ai", "media"],
        "portfolio": ["Coinbase", "Zcash", "OpenSea"],
        "verified": True,
    },
    {
        "name": "Alexis Ohanian",
        "bio": "Co-founder of Reddit. Founder of Seven Seven Six fund. Active angel across consumer, crypto, and sports tech.",
        "location": "Los Angeles, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/alexisohanian",
        "website": "https://sevensevensix.com",
        "type": "angel",
        "check_min": 100000,
        "check_max": 2000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["consumer", "crypto", "sports-tech", "marketplace", "saas"],
        "portfolio": ["Reddit", "Initialized Capital", "Instacart"],
        "verified": True,
    },
    {
        "name": "Jason Calacanis",
        "bio": "Angel investor and entrepreneur. Host of This Week in Startups. Syndicate investor with 300+ angel investments.",
        "location": "Los Angeles, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/jason",
        "website": "https://calacanis.com",
        "type": "angel",
        "check_min": 25000,
        "check_max": 500000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "consumer", "marketplace", "ai", "fintech"],
        "portfolio": ["Uber", "Robinhood", "Calm", "Thumbtack"],
        "verified": True,
    },
    {
        "name": "Cyan Banister",
        "bio": "Partner at Long Journey Ventures. Former partner at Founders Fund. Angel investor in 100+ startups.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/cyantist",
        "type": "angel",
        "check_min": 50000,
        "check_max": 500000,
        "stages": ["pre-seed", "seed"],
        "industries": ["consumer", "saas", "gaming", "ai", "crypto"],
        "portfolio": ["SpaceX", "Niantic", "Postmates", "Uber"],
        "verified": True,
    },
    {
        "name": "Daniel Gross",
        "bio": "Co-founder of Pioneer. Former AI lead at Apple (Siri). Partner at Y Combinator. Active angel in AI.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/danielgross",
        "type": "angel",
        "check_min": 100000,
        "check_max": 1000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["ai", "developer-tools", "saas"],
        "portfolio": ["Codeium", "Mistral", "Pioneer"],
        "verified": True,
    },
    {
        "name": "Garry Tan",
        "bio": "CEO of Y Combinator. Previously co-founder of Initialized Capital. Early investor in Coinbase, Instacart, Reddit.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/garrytan",
        "type": "angel",
        "check_min": 500000,
        "check_max": 10000000,
        "stages": ["pre-seed", "seed", "series-a"],
        "industries": ["saas", "fintech", "consumer", "ai", "crypto"],
        "portfolio": ["Coinbase", "Instacart", "Reddit", "Flexport"],
        "verified": True,
    },
    {
        "name": "Sahil Lavingia",
        "bio": "Founder and CEO of Gumroad. Angel investor in 100+ startups. Known for open investing and small checks.",
        "location": "Remote",
        "country": "USA",
        "twitter_url": "https://twitter.com/shl",
        "website": "https://sahillavingia.com",
        "type": "angel",
        "check_min": 10000,
        "check_max": 100000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "creator-economy", "marketplace", "consumer"],
        "portfolio": ["Figma", "Notion", "Mercury"],
        "verified": True,
    },
    {
        "name": "Pieter Levels",
        "bio": "Indie maker and angel investor. Creator of Nomad List and Remote OK. Invests in solo founders and indie SaaS.",
        "location": "Amsterdam",
        "country": "Netherlands",
        "twitter_url": "https://twitter.com/levelsio",
        "website": "https://levels.io",
        "type": "angel",
        "check_min": 5000,
        "check_max": 50000,
        "stages": ["pre-seed"],
        "industries": ["saas", "consumer", "creator-economy", "marketplace"],
        "portfolio": [],
        "verified": True,
    },
    {
        "name": "Andrew Wilkinson",
        "bio": "Co-founder of Tiny Capital. Acquires and grows internet businesses. Minority angel investor in tech companies.",
        "location": "Victoria, BC",
        "country": "Canada",
        "twitter_url": "https://twitter.com/awilkinson",
        "website": "https://tinycapital.com",
        "type": "angel",
        "check_min": 50000,
        "check_max": 500000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "marketplace", "consumer", "media"],
        "portfolio": ["Dribbble", "Metalab", "Flow"],
        "verified": True,
    },
    # ── AI / DEEP TECH FOCUSED ─────────────────────────────────────────────
    {
        "name": "Nat Friedman",
        "bio": "Former CEO of GitHub. Co-founder of Sundai Club. Active angel in AI, developer tools, and open source.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/natfriedman",
        "type": "angel",
        "check_min": 250000,
        "check_max": 3000000,
        "stages": ["seed", "series-a"],
        "industries": ["ai", "developer-tools", "open-source", "saas"],
        "portfolio": ["GitHub Copilot", "Mistral", "Perplexity"],
        "verified": True,
    },
    {
        "name": "Greg Brockman",
        "bio": "Co-founder and President of OpenAI. Angel investor in AI-first startups.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/gdb",
        "type": "angel",
        "check_min": 100000,
        "check_max": 1000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["ai", "developer-tools", "saas"],
        "portfolio": ["OpenAI"],
        "verified": True,
    },
    {
        "name": "Andrej Karpathy",
        "bio": "Former Director of AI at Tesla, co-founder of OpenAI. Angel investor in AI and robotics.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/karpathy",
        "type": "angel",
        "check_min": 50000,
        "check_max": 500000,
        "stages": ["pre-seed", "seed"],
        "industries": ["ai", "robotics", "developer-tools"],
        "portfolio": [],
        "verified": True,
    },
    {
        "name": "Reid Hoffman",
        "bio": "Co-founder of LinkedIn. Partner at Greylock. One of the most active angel investors in Silicon Valley.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/reidhoffman",
        "website": "https://greylock.com",
        "type": "angel",
        "check_min": 500000,
        "check_max": 10000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["saas", "ai", "marketplace", "fintech", "consumer"],
        "portfolio": ["Facebook", "Airbnb", "Zynga", "PayPal", "Convoy"],
        "verified": True,
    },
    # ── FINTECH FOCUSED ──────────────────────────────────────────────────
    {
        "name": "Max Levchin",
        "bio": "Co-founder of PayPal and Affirm. Active angel investor in fintech and consumer.",
        "location": "San Francisco, CA",
        "country": "USA",
        "type": "angel",
        "check_min": 250000,
        "check_max": 5000000,
        "stages": ["seed", "series-a"],
        "industries": ["fintech", "consumer", "saas"],
        "portfolio": ["PayPal", "Affirm", "Yelp", "Evernote"],
        "verified": True,
    },
    {
        "name": "Patrick Collison",
        "bio": "Co-founder and CEO of Stripe. Angel investor in science and technology. Board member at various startups.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/patrickc",
        "type": "angel",
        "check_min": 500000,
        "check_max": 10000000,
        "stages": ["seed", "series-a"],
        "industries": ["fintech", "saas", "ai", "developer-tools", "science"],
        "portfolio": ["Stripe", "Figma", "Notion", "Brex"],
        "verified": True,
    },
    {
        "name": "John Collison",
        "bio": "Co-founder and President of Stripe. Angel investor in fintech and SaaS companies.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/collision",
        "type": "angel",
        "check_min": 250000,
        "check_max": 5000000,
        "stages": ["seed", "series-a"],
        "industries": ["fintech", "saas", "developer-tools"],
        "portfolio": ["Stripe", "Brex", "Mercury"],
        "verified": True,
    },
    # ── FEMALE ANGELS ──────────────────────────────────────────────────────
    {
        "name": "Aileen Lee",
        "bio": "Founder of Cowboy Ventures. Coined the term 'unicorn' for startups. Former partner at Kleiner Perkins.",
        "location": "Palo Alto, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/aileenlee",
        "website": "https://cowboy.vc",
        "type": "vc",
        "check_min": 500000,
        "check_max": 5000000,
        "stages": ["seed", "series-a"],
        "industries": ["saas", "consumer", "fintech", "ai", "marketplace"],
        "portfolio": ["Dollar Shave Club", "Life360", "Rent the Runway"],
        "verified": True,
    },
    {
        "name": "Kirsten Green",
        "bio": "Founder of Forerunner Ventures. Focuses on consumer-facing companies. Early investor in Warby Parker, Dollar Shave Club.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/kirstenagreen",
        "website": "https://forerunnerventures.com",
        "type": "vc",
        "check_min": 1000000,
        "check_max": 10000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["consumer", "e-commerce", "marketplace", "health", "beauty"],
        "portfolio": ["Warby Parker", "Dollar Shave Club", "Glossier", "Outdoor Voices"],
        "verified": True,
    },
    {
        "name": "Joanna Coles",
        "bio": "Former Editor-in-Chief of Cosmopolitan. Media executive and angel investor in consumer and media startups.",
        "location": "New York, NY",
        "country": "USA",
        "type": "angel",
        "check_min": 25000,
        "check_max": 250000,
        "stages": ["pre-seed", "seed"],
        "industries": ["media", "consumer", "health", "beauty", "e-commerce"],
        "portfolio": [],
        "verified": False,
    },
    {
        "name": "Arlan Hamilton",
        "bio": "Founder of Backstage Capital. Raised a $5M fund while homeless. Investing in underrepresented founders.",
        "location": "Los Angeles, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/arlanwashere",
        "website": "https://backstagecapital.com",
        "type": "vc",
        "check_min": 25000,
        "check_max": 100000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "consumer", "health", "fintech", "media"],
        "portfolio": [],
        "verified": True,
    },
    # ── B2B / ENTERPRISE SaaS ─────────────────────────────────────────────
    {
        "name": "David Sacks",
        "bio": "Co-founder of Yammer and Craft Ventures. Former COO of PayPal. Angel and VC in B2B SaaS.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/davidsacks",
        "website": "https://craftventures.com",
        "type": "vc",
        "check_min": 500000,
        "check_max": 10000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["saas", "fintech", "crypto", "ai", "marketplace"],
        "portfolio": ["Yammer", "Zenefits", "Bird", "Houzz", "SpaceX"],
        "verified": True,
    },
    {
        "name": "Aaron Levie",
        "bio": "Co-founder and CEO of Box. Angel investor in enterprise SaaS and cloud companies.",
        "location": "Redwood City, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/levie",
        "type": "angel",
        "check_min": 50000,
        "check_max": 500000,
        "stages": ["seed", "series-a"],
        "industries": ["saas", "enterprise", "ai", "developer-tools"],
        "portfolio": ["Box"],
        "verified": True,
    },
    {
        "name": "Hiten Shah",
        "bio": "Co-founder of KISSmetrics, Crazy Egg, and FYI. Active angel investor in SaaS startups.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/hnshah",
        "type": "angel",
        "check_min": 10000,
        "check_max": 100000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "developer-tools", "analytics", "marketing"],
        "portfolio": ["Slack", "Zapier"],
        "verified": True,
    },
    # ── CRYPTO / WEB3 ─────────────────────────────────────────────────────
    {
        "name": "Brian Armstrong",
        "bio": "Co-founder and CEO of Coinbase. Angel investor in crypto and Web3 companies through GV and personal portfolio.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/brian_armstrong",
        "type": "angel",
        "check_min": 250000,
        "check_max": 5000000,
        "stages": ["seed", "series-a"],
        "industries": ["crypto", "fintech", "ai", "developer-tools"],
        "portfolio": ["Coinbase", "OpenSea"],
        "verified": True,
    },
    {
        "name": "Chris Dixon",
        "bio": "General Partner at a16z Crypto. Co-founder of Hunch and SiteAdvisor. Pioneer in crypto investing.",
        "location": "New York, NY",
        "country": "USA",
        "twitter_url": "https://twitter.com/cdixon",
        "website": "https://a16zcrypto.com",
        "type": "vc",
        "check_min": 1000000,
        "check_max": 20000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["crypto", "web3", "ai", "developer-tools"],
        "portfolio": ["Coinbase", "OpenSea", "Dapper Labs", "Compound"],
        "verified": True,
    },
    # ── EUROPEAN ANGELS ──────────────────────────────────────────────────
    {
        "name": "Niklas Zennström",
        "bio": "Co-founder of Skype and Kazaa. Founder of Atomico VC. Invests in European tech companies.",
        "location": "London",
        "country": "UK",
        "twitter_url": "https://twitter.com/zennstrom",
        "website": "https://atomico.com",
        "type": "vc",
        "check_min": 2000000,
        "check_max": 30000000,
        "stages": ["series-a", "series-b", "growth"],
        "industries": ["saas", "consumer", "fintech", "ai", "climate"],
        "portfolio": ["Klarna", "Supercell", "Rovio", "Lilium"],
        "verified": True,
    },
    {
        "name": "Daniel Ek",
        "bio": "Co-founder and CEO of Spotify. Active angel investor in music, health, and European tech.",
        "location": "Stockholm",
        "country": "Sweden",
        "twitter_url": "https://twitter.com/eldsjal",
        "type": "angel",
        "check_min": 1000000,
        "check_max": 20000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["consumer", "health", "ai", "defense", "media"],
        "portfolio": ["Spotify", "Primer", "Northvolt"],
        "verified": True,
    },
    {
        "name": "Taavet Hinrikus",
        "bio": "Co-founder of Wise (TransferWise). Active European angel investor, especially fintech and SaaS.",
        "location": "London",
        "country": "UK",
        "twitter_url": "https://twitter.com/taavet",
        "type": "angel",
        "check_min": 100000,
        "check_max": 2000000,
        "stages": ["pre-seed", "seed", "series-a"],
        "industries": ["fintech", "saas", "marketplace", "consumer"],
        "portfolio": ["Wise", "Pipedrive", "Skype"],
        "verified": True,
    },
    {
        "name": "Ott Kaukver",
        "bio": "Angel investor and advisor. Former CTO of Twilio and Skype. Invests in developer tools and SaaS.",
        "location": "Tallinn",
        "country": "Estonia",
        "type": "angel",
        "check_min": 25000,
        "check_max": 250000,
        "stages": ["pre-seed", "seed"],
        "industries": ["developer-tools", "saas", "fintech"],
        "portfolio": [],
        "verified": False,
    },
    {
        "name": "Jaan Tallinn",
        "bio": "Co-founder of Skype and Kazaa. AI safety investor. Co-founder of CSER and MIRI. Invests in AI and deep tech.",
        "location": "Tallinn",
        "country": "Estonia",
        "twitter_url": "https://twitter.com/jaan_tallinn",
        "type": "angel",
        "check_min": 100000,
        "check_max": 2000000,
        "stages": ["seed", "series-a"],
        "industries": ["ai", "biotech", "deep-tech", "climate"],
        "portfolio": ["DeepMind", "Skype"],
        "verified": True,
    },
    # ── EDTECH FOCUSED ───────────────────────────────────────────────────
    {
        "name": "Sal Khan",
        "bio": "Founder of Khan Academy. Education-focused angel investor and philanthropist.",
        "location": "Mountain View, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/salkhanacademy",
        "type": "angel",
        "check_min": 25000,
        "check_max": 250000,
        "stages": ["pre-seed", "seed"],
        "industries": ["edtech", "ai", "consumer"],
        "portfolio": ["Khan Academy"],
        "verified": True,
    },
    # ── HEALTH / BIOTECH ──────────────────────────────────────────────────
    {
        "name": "Anne Wojcicki",
        "bio": "Co-founder and CEO of 23andMe. Angel investor in genomics, biotech, and health tech.",
        "location": "Sunnyvale, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/annewojcicki",
        "type": "angel",
        "check_min": 100000,
        "check_max": 2000000,
        "stages": ["seed", "series-a"],
        "industries": ["biotech", "health", "ai", "consumer"],
        "portfolio": ["23andMe", "Noom"],
        "verified": True,
    },
    # ── CLIMATE / DEEPTECH ───────────────────────────────────────────────
    {
        "name": "Bill Gates",
        "bio": "Co-founder of Microsoft. Founder of Breakthrough Energy Ventures. Invests in climate and global health.",
        "location": "Medina, WA",
        "country": "USA",
        "twitter_url": "https://twitter.com/billgates",
        "website": "https://breakthroughenergy.org",
        "type": "angel",
        "check_min": 5000000,
        "check_max": 100000000,
        "stages": ["series-a", "series-b", "growth"],
        "industries": ["climate", "biotech", "health", "energy", "ai"],
        "portfolio": ["TerraPower", "Beyond Meat", "Impossible Foods", "Ginkgo Bioworks"],
        "verified": True,
    },
    # ── MARKETPLACE / CONSUMER ──────────────────────────────────────────
    {
        "name": "Roelof Botha",
        "bio": "Partner at Sequoia Capital. Former CFO of PayPal. Led investments in YouTube, Instagram, and MongoDB.",
        "location": "Menlo Park, CA",
        "country": "USA",
        "type": "vc",
        "check_min": 2000000,
        "check_max": 50000000,
        "stages": ["series-a", "series-b", "growth"],
        "industries": ["consumer", "saas", "fintech", "marketplace", "ai"],
        "portfolio": ["YouTube", "Instagram", "MongoDB", "Unity", "Square"],
        "verified": True,
    },
    {
        "name": "Tony Xu",
        "bio": "Co-founder and CEO of DoorDash. Angel investor in consumer marketplace and logistics startups.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/t_xu",
        "type": "angel",
        "check_min": 100000,
        "check_max": 2000000,
        "stages": ["seed", "series-a"],
        "industries": ["marketplace", "consumer", "logistics", "saas"],
        "portfolio": ["DoorDash"],
        "verified": True,
    },
    # ── ACCELERATORS ────────────────────────────────────────────────────
    {
        "name": "Y Combinator",
        "bio": "The world's top startup accelerator. $500K investment for 7% equity. Backed Airbnb, Stripe, Dropbox, Coinbase.",
        "location": "San Francisco, CA",
        "country": "USA",
        "website": "https://ycombinator.com",
        "twitter_url": "https://twitter.com/ycombinator",
        "type": "accelerator",
        "check_min": 500000,
        "check_max": 500000,
        "stages": ["pre-seed"],
        "industries": ["saas", "ai", "fintech", "consumer", "marketplace", "biotech", "developer-tools"],
        "portfolio": ["Airbnb", "Stripe", "Dropbox", "Coinbase", "Reddit", "DoorDash"],
        "verified": True,
    },
    {
        "name": "Techstars",
        "bio": "Global startup accelerator network. $120K investment for 6% equity. 3,000+ companies backed worldwide.",
        "location": "Boulder, CO",
        "country": "USA",
        "website": "https://techstars.com",
        "twitter_url": "https://twitter.com/techstars",
        "type": "accelerator",
        "check_min": 120000,
        "check_max": 120000,
        "stages": ["pre-seed"],
        "industries": ["saas", "fintech", "health", "consumer", "ai", "smart-cities"],
        "portfolio": ["Sendgrid", "Sphero", "ClassPass", "Digital Ocean"],
        "verified": True,
    },
    {
        "name": "500 Global",
        "bio": "Venture capital firm and accelerator with $2.7B AUM. Invests globally in early-stage tech companies.",
        "location": "San Francisco, CA",
        "country": "USA",
        "website": "https://500.co",
        "twitter_url": "https://twitter.com/500global",
        "type": "accelerator",
        "check_min": 150000,
        "check_max": 1000000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "fintech", "marketplace", "consumer", "ai"],
        "portfolio": ["Canva", "Grab", "Talkdesk", "Credit Karma"],
        "verified": True,
    },
    # ── ADDITIONAL WELL-KNOWN ANGELS ─────────────────────────────────────
    {
        "name": "Chamath Palihapitiya",
        "bio": "Founder of Social Capital. Former VP at Facebook. Active SPAC investor and angel in tech companies.",
        "location": "Palo Alto, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/chamath",
        "website": "https://socialcapital.com",
        "type": "vc",
        "check_min": 1000000,
        "check_max": 50000000,
        "stages": ["seed", "series-a", "series-b", "growth"],
        "industries": ["saas", "fintech", "health", "climate", "ai"],
        "portfolio": ["Facebook", "Slack", "SoFi", "Box", "Palantir"],
        "verified": True,
    },
    {
        "name": "Michael Seibel",
        "bio": "Managing Director at Y Combinator. Co-founder of Twitch and Justin.tv. Active mentor and angel investor.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/mwseibel",
        "type": "angel",
        "check_min": 25000,
        "check_max": 250000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "consumer", "marketplace", "ai"],
        "portfolio": ["Twitch", "Reddit"],
        "verified": True,
    },
    {
        "name": "Kevin Rose",
        "bio": "Co-founder of Digg. Partner at True Ventures. Angel investor in consumer and crypto startups.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/kevinrose",
        "type": "angel",
        "check_min": 25000,
        "check_max": 250000,
        "stages": ["pre-seed", "seed"],
        "industries": ["consumer", "crypto", "health", "saas"],
        "portfolio": ["Twitter", "Facebook", "Square", "Foursquare"],
        "verified": True,
    },
    {
        "name": "Tim Draper",
        "bio": "Founder of Draper Associates and DFJ. Known for early bets on Hotmail, Skype, Baidu, and Tesla.",
        "location": "San Mateo, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/timdraper",
        "website": "https://draper.vc",
        "type": "vc",
        "check_min": 500000,
        "check_max": 20000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["saas", "crypto", "fintech", "ai", "consumer"],
        "portfolio": ["Hotmail", "Skype", "Baidu", "Tesla", "SpaceX"],
        "verified": True,
    },
    {
        "name": "Dave McClure",
        "bio": "Founder of 500 Startups. One of the most prolific early-stage investors with 1,500+ companies backed.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/davemcclure",
        "type": "angel",
        "check_min": 25000,
        "check_max": 250000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "consumer", "marketplace", "fintech"],
        "portfolio": ["Canva", "Grab", "MakerBot"],
        "verified": True,
    },
    {
        "name": "Keith Rabois",
        "bio": "General Partner at Founders Fund. Former EVP at PayPal. Board member at Square, Yelp, LinkedIn.",
        "location": "Miami, FL",
        "country": "USA",
        "twitter_url": "https://twitter.com/rabois",
        "type": "vc",
        "check_min": 1000000,
        "check_max": 20000000,
        "stages": ["seed", "series-a", "series-b"],
        "industries": ["fintech", "saas", "real-estate", "marketplace"],
        "portfolio": ["PayPal", "Square", "Yelp", "LinkedIn", "Opendoor"],
        "verified": True,
    },
    {
        "name": "Vinod Khosla",
        "bio": "Founder of Khosla Ventures and co-founder of Sun Microsystems. Invests in deep tech, AI, and climate.",
        "location": "Menlo Park, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/vkhosla",
        "website": "https://khoslaventures.com",
        "type": "vc",
        "check_min": 1000000,
        "check_max": 50000000,
        "stages": ["seed", "series-a", "series-b", "growth"],
        "industries": ["ai", "climate", "biotech", "energy", "deep-tech"],
        "portfolio": ["DoorDash", "Square", "Stripe", "OpenAI"],
        "verified": True,
    },
    {
        "name": "Naval Ravikant",
        "bio": "Repeat entry — alias AngelList, investing in founders and transformative technologies.",
        "location": "San Francisco, CA",
        "country": "USA",
        "type": "angel",
        "check_min": 50000,
        "check_max": 500000,
        "stages": ["pre-seed", "seed"],
        "industries": ["saas", "crypto", "ai"],
        "portfolio": [],
        "verified": False,
    },
    {
        "name": "Josh Buckley",
        "bio": "CEO of Product Hunt. Angel investor in consumer, gaming, and SaaS. Runs Buckley Ventures.",
        "location": "San Francisco, CA",
        "country": "USA",
        "twitter_url": "https://twitter.com/joshbuckley",
        "type": "angel",
        "check_min": 25000,
        "check_max": 250000,
        "stages": ["pre-seed", "seed"],
        "industries": ["consumer", "gaming", "saas", "marketplace"],
        "portfolio": ["Product Hunt"],
        "verified": True,
    },
]

# Remove duplicate by name (Naval appears twice by mistake above)
seen = set()
UNIQUE_INVESTORS = []
for inv in INVESTORS:
    key = inv["name"].lower().strip()
    if key not in seen:
        seen.add(key)
        UNIQUE_INVESTORS.append(inv)

INVESTORS = UNIQUE_INVESTORS
print(f"✅ Loaded {len(INVESTORS)} investors in seed data")
